// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/kdoctor-io/kdoctor/pkg/k8s/apis/kdoctor.io/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAppHttpHealthies implements AppHttpHealthyInterface
type FakeAppHttpHealthies struct {
	Fake *FakeKdoctorV1beta1
}

var apphttphealthiesResource = schema.GroupVersionResource{Group: "kdoctor.io", Version: "v1beta1", Resource: "apphttphealthies"}

var apphttphealthiesKind = schema.GroupVersionKind{Group: "kdoctor.io", Version: "v1beta1", Kind: "AppHttpHealthy"}

// Get takes name of the appHttpHealthy, and returns the corresponding appHttpHealthy object, and an error if there is any.
func (c *FakeAppHttpHealthies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.AppHttpHealthy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(apphttphealthiesResource, name), &v1beta1.AppHttpHealthy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AppHttpHealthy), err
}

// List takes label and field selectors, and returns the list of AppHttpHealthies that match those selectors.
func (c *FakeAppHttpHealthies) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.AppHttpHealthyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(apphttphealthiesResource, apphttphealthiesKind, opts), &v1beta1.AppHttpHealthyList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.AppHttpHealthyList{ListMeta: obj.(*v1beta1.AppHttpHealthyList).ListMeta}
	for _, item := range obj.(*v1beta1.AppHttpHealthyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested appHttpHealthies.
func (c *FakeAppHttpHealthies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(apphttphealthiesResource, opts))
}

// Create takes the representation of a appHttpHealthy and creates it.  Returns the server's representation of the appHttpHealthy, and an error, if there is any.
func (c *FakeAppHttpHealthies) Create(ctx context.Context, appHttpHealthy *v1beta1.AppHttpHealthy, opts v1.CreateOptions) (result *v1beta1.AppHttpHealthy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(apphttphealthiesResource, appHttpHealthy), &v1beta1.AppHttpHealthy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AppHttpHealthy), err
}

// Update takes the representation of a appHttpHealthy and updates it. Returns the server's representation of the appHttpHealthy, and an error, if there is any.
func (c *FakeAppHttpHealthies) Update(ctx context.Context, appHttpHealthy *v1beta1.AppHttpHealthy, opts v1.UpdateOptions) (result *v1beta1.AppHttpHealthy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(apphttphealthiesResource, appHttpHealthy), &v1beta1.AppHttpHealthy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AppHttpHealthy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAppHttpHealthies) UpdateStatus(ctx context.Context, appHttpHealthy *v1beta1.AppHttpHealthy, opts v1.UpdateOptions) (*v1beta1.AppHttpHealthy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(apphttphealthiesResource, "status", appHttpHealthy), &v1beta1.AppHttpHealthy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AppHttpHealthy), err
}

// Delete takes name of the appHttpHealthy and deletes it. Returns an error if one occurs.
func (c *FakeAppHttpHealthies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(apphttphealthiesResource, name, opts), &v1beta1.AppHttpHealthy{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAppHttpHealthies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(apphttphealthiesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.AppHttpHealthyList{})
	return err
}

// Patch applies the patch and returns the patched appHttpHealthy.
func (c *FakeAppHttpHealthies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.AppHttpHealthy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(apphttphealthiesResource, name, pt, data, subresources...), &v1beta1.AppHttpHealthy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AppHttpHealthy), err
}
