// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/kdoctor-io/kdoctor/pkg/k8s/apis/kdoctor.io/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNetReaches implements NetReachInterface
type FakeNetReaches struct {
	Fake *FakeKdoctorV1beta1
}

var netreachesResource = schema.GroupVersionResource{Group: "kdoctor.io", Version: "v1beta1", Resource: "netreaches"}

var netreachesKind = schema.GroupVersionKind{Group: "kdoctor.io", Version: "v1beta1", Kind: "NetReach"}

// Get takes name of the netReach, and returns the corresponding netReach object, and an error if there is any.
func (c *FakeNetReaches) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.NetReach, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(netreachesResource, name), &v1beta1.NetReach{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NetReach), err
}

// List takes label and field selectors, and returns the list of NetReaches that match those selectors.
func (c *FakeNetReaches) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.NetReachList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(netreachesResource, netreachesKind, opts), &v1beta1.NetReachList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.NetReachList{ListMeta: obj.(*v1beta1.NetReachList).ListMeta}
	for _, item := range obj.(*v1beta1.NetReachList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested netReaches.
func (c *FakeNetReaches) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(netreachesResource, opts))
}

// Create takes the representation of a netReach and creates it.  Returns the server's representation of the netReach, and an error, if there is any.
func (c *FakeNetReaches) Create(ctx context.Context, netReach *v1beta1.NetReach, opts v1.CreateOptions) (result *v1beta1.NetReach, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(netreachesResource, netReach), &v1beta1.NetReach{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NetReach), err
}

// Update takes the representation of a netReach and updates it. Returns the server's representation of the netReach, and an error, if there is any.
func (c *FakeNetReaches) Update(ctx context.Context, netReach *v1beta1.NetReach, opts v1.UpdateOptions) (result *v1beta1.NetReach, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(netreachesResource, netReach), &v1beta1.NetReach{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NetReach), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNetReaches) UpdateStatus(ctx context.Context, netReach *v1beta1.NetReach, opts v1.UpdateOptions) (*v1beta1.NetReach, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(netreachesResource, "status", netReach), &v1beta1.NetReach{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NetReach), err
}

// Delete takes name of the netReach and deletes it. Returns an error if one occurs.
func (c *FakeNetReaches) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(netreachesResource, name, opts), &v1beta1.NetReach{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetReaches) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(netreachesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.NetReachList{})
	return err
}

// Patch applies the patch and returns the patched netReach.
func (c *FakeNetReaches) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.NetReach, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(netreachesResource, name, pt, data, subresources...), &v1beta1.NetReach{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NetReach), err
}
