// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/kdoctor-io/kdoctor/pkg/k8s/apis/kdoctor.io/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHttpAppHealthies implements HttpAppHealthyInterface
type FakeHttpAppHealthies struct {
	Fake *FakeKdoctorV1beta1
}

var httpapphealthiesResource = schema.GroupVersionResource{Group: "kdoctor.io", Version: "v1beta1", Resource: "httpapphealthies"}

var httpapphealthiesKind = schema.GroupVersionKind{Group: "kdoctor.io", Version: "v1beta1", Kind: "HttpAppHealthy"}

// Get takes name of the httpAppHealthy, and returns the corresponding httpAppHealthy object, and an error if there is any.
func (c *FakeHttpAppHealthies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.HttpAppHealthy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(httpapphealthiesResource, name), &v1beta1.HttpAppHealthy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HttpAppHealthy), err
}

// List takes label and field selectors, and returns the list of HttpAppHealthies that match those selectors.
func (c *FakeHttpAppHealthies) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.HttpAppHealthyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(httpapphealthiesResource, httpapphealthiesKind, opts), &v1beta1.HttpAppHealthyList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.HttpAppHealthyList{ListMeta: obj.(*v1beta1.HttpAppHealthyList).ListMeta}
	for _, item := range obj.(*v1beta1.HttpAppHealthyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested httpAppHealthies.
func (c *FakeHttpAppHealthies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(httpapphealthiesResource, opts))
}

// Create takes the representation of a httpAppHealthy and creates it.  Returns the server's representation of the httpAppHealthy, and an error, if there is any.
func (c *FakeHttpAppHealthies) Create(ctx context.Context, httpAppHealthy *v1beta1.HttpAppHealthy, opts v1.CreateOptions) (result *v1beta1.HttpAppHealthy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(httpapphealthiesResource, httpAppHealthy), &v1beta1.HttpAppHealthy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HttpAppHealthy), err
}

// Update takes the representation of a httpAppHealthy and updates it. Returns the server's representation of the httpAppHealthy, and an error, if there is any.
func (c *FakeHttpAppHealthies) Update(ctx context.Context, httpAppHealthy *v1beta1.HttpAppHealthy, opts v1.UpdateOptions) (result *v1beta1.HttpAppHealthy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(httpapphealthiesResource, httpAppHealthy), &v1beta1.HttpAppHealthy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HttpAppHealthy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHttpAppHealthies) UpdateStatus(ctx context.Context, httpAppHealthy *v1beta1.HttpAppHealthy, opts v1.UpdateOptions) (*v1beta1.HttpAppHealthy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(httpapphealthiesResource, "status", httpAppHealthy), &v1beta1.HttpAppHealthy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HttpAppHealthy), err
}

// Delete takes name of the httpAppHealthy and deletes it. Returns an error if one occurs.
func (c *FakeHttpAppHealthies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(httpapphealthiesResource, name, opts), &v1beta1.HttpAppHealthy{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHttpAppHealthies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(httpapphealthiesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.HttpAppHealthyList{})
	return err
}

// Patch applies the patch and returns the patched httpAppHealthy.
func (c *FakeHttpAppHealthies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.HttpAppHealthy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(httpapphealthiesResource, name, pt, data, subresources...), &v1beta1.HttpAppHealthy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HttpAppHealthy), err
}
