// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/kdoctor-io/kdoctor/pkg/k8s/apis/kdoctor.io/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNetReachHealthies implements NetReachHealthyInterface
type FakeNetReachHealthies struct {
	Fake *FakeKdoctorV1beta1
}

var netreachhealthiesResource = schema.GroupVersionResource{Group: "kdoctor.io", Version: "v1beta1", Resource: "netreachhealthies"}

var netreachhealthiesKind = schema.GroupVersionKind{Group: "kdoctor.io", Version: "v1beta1", Kind: "NetReachHealthy"}

// Get takes name of the netReachHealthy, and returns the corresponding netReachHealthy object, and an error if there is any.
func (c *FakeNetReachHealthies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.NetReachHealthy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(netreachhealthiesResource, name), &v1beta1.NetReachHealthy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NetReachHealthy), err
}

// List takes label and field selectors, and returns the list of NetReachHealthies that match those selectors.
func (c *FakeNetReachHealthies) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.NetReachHealthyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(netreachhealthiesResource, netreachhealthiesKind, opts), &v1beta1.NetReachHealthyList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.NetReachHealthyList{ListMeta: obj.(*v1beta1.NetReachHealthyList).ListMeta}
	for _, item := range obj.(*v1beta1.NetReachHealthyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested netReachHealthies.
func (c *FakeNetReachHealthies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(netreachhealthiesResource, opts))
}

// Create takes the representation of a netReachHealthy and creates it.  Returns the server's representation of the netReachHealthy, and an error, if there is any.
func (c *FakeNetReachHealthies) Create(ctx context.Context, netReachHealthy *v1beta1.NetReachHealthy, opts v1.CreateOptions) (result *v1beta1.NetReachHealthy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(netreachhealthiesResource, netReachHealthy), &v1beta1.NetReachHealthy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NetReachHealthy), err
}

// Update takes the representation of a netReachHealthy and updates it. Returns the server's representation of the netReachHealthy, and an error, if there is any.
func (c *FakeNetReachHealthies) Update(ctx context.Context, netReachHealthy *v1beta1.NetReachHealthy, opts v1.UpdateOptions) (result *v1beta1.NetReachHealthy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(netreachhealthiesResource, netReachHealthy), &v1beta1.NetReachHealthy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NetReachHealthy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNetReachHealthies) UpdateStatus(ctx context.Context, netReachHealthy *v1beta1.NetReachHealthy, opts v1.UpdateOptions) (*v1beta1.NetReachHealthy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(netreachhealthiesResource, "status", netReachHealthy), &v1beta1.NetReachHealthy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NetReachHealthy), err
}

// Delete takes name of the netReachHealthy and deletes it. Returns an error if one occurs.
func (c *FakeNetReachHealthies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(netreachhealthiesResource, name, opts), &v1beta1.NetReachHealthy{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetReachHealthies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(netreachhealthiesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.NetReachHealthyList{})
	return err
}

// Patch applies the patch and returns the patched netReachHealthy.
func (c *FakeNetReachHealthies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.NetReachHealthy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(netreachhealthiesResource, name, pt, data, subresources...), &v1beta1.NetReachHealthy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NetReachHealthy), err
}
