- name: pr/not-ready
  description: not ready for merging
  color: d73a4a
- name: release/bug
  description: bug pr recoded in new release
  color: d73a4a
- name: release/feature-changed
  description: feature pr recoded in new release
  color: 0075ca
- name: release/feature-new
  description: feature pr recoded in new release
  color: 0075ca
- name: release/none
  description: should not recoded in new release
  color: 0075ca