site_name: kdoctor
docs_dir: docs
site_dir: site
repo_name: kdoctor-io/kdoctor
repo_url: https://github.com/kdoctor-io/kdoctor
# remote branch for mkdocs gh-deploy
remote_branch: github_pages
theme:
  name: material
  custom_dir: docs/overrides
  # The maximum depth of the navigation tree in the sidebar
  navigation_depth: 2
  palette:
    scheme: default
    primary: blue
    language: zh
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share

plugins:
  - tags
  - search

extra:
  version:
    provider: mike

markdown_extensions:
  - meta
  - toc
  - tables
  - fenced_code
  - tables
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - README.md
  - Installation:
      - Installation: usage/install.md
      - Quickly Started: usage/get-started-kind.md
  - Usage:
      - AppHttpHealthy: usage/apphttphealthy.md
      - NetReach: usage/netreach.md
      - NetDns: usage/netdns.md
      - Debug: usage/debug.md
  - Concepts:
      - Architecture: reference/arch.md
      - Runtime: concepts/runtime.md
  - Reference:
      - AppHttpHealthy: reference/apphttphealthy.md
      - NetReach: reference/netreach.md
      - NetDns: reference/netdns.md
      - kdoctor-controller: reference/kdoctor-controller.md
      - kdoctor-agent: reference/kdoctor-agent.md
      - Report: reference/report.md
      - Performance: usage/performance.md
  - Development:
      - Release workflow: develop/release.md
      - Roadmap: develop/roadmap.md
      - Contribution: develop/contributing.md
