// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package healthy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetHealthyLivenessOKCode is the HTTP code returned for type GetHealthyLivenessOK
const GetHealthyLivenessOKCode int = 200

/*
GetHealthyLivenessOK Success

swagger:response getHealthyLivenessOK
*/
type GetHealthyLivenessOK struct {
}

// NewGetHealthyLivenessOK creates GetHealthyLivenessOK with default headers values
func NewGetHealthyLivenessOK() *GetHealthyLivenessOK {

	return &GetHealthyLivenessOK{}
}

// WriteResponse to the client
func (o *GetHealthyLivenessOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetHealthyLivenessInternalServerErrorCode is the HTTP code returned for type GetHealthyLivenessInternalServerError
const GetHealthyLivenessInternalServerErrorCode int = 500

/*
GetHealthyLivenessInternalServerError Failed

swagger:response getHealthyLivenessInternalServerError
*/
type GetHealthyLivenessInternalServerError struct {
}

// NewGetHealthyLivenessInternalServerError creates GetHealthyLivenessInternalServerError with default headers values
func NewGetHealthyLivenessInternalServerError() *GetHealthyLivenessInternalServerError {

	return &GetHealthyLivenessInternalServerError{}
}

// WriteResponse to the client
func (o *GetHealthyLivenessInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
