// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	internalinterfaces "github.com/kdoctor-io/kdoctor/pkg/k8s/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// HttpAppHealthies returns a HttpAppHealthyInformer.
	HttpAppHealthies() HttpAppHealthyInformer
	// NetReachHealthies returns a NetReachHealthyInformer.
	NetReachHealthies() NetReachHealthyInformer
	// Netdnses returns a NetdnsInformer.
	Netdnses() NetdnsInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// HttpAppHealthies returns a HttpAppHealthyInformer.
func (v *version) HttpAppHealthies() HttpAppHealthyInformer {
	return &httpAppHealthyInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// NetReachHealthies returns a NetReachHealthyInformer.
func (v *version) NetReachHealthies() NetReachHealthyInformer {
	return &netReachHealthyInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// Netdnses returns a NetdnsInformer.
func (v *version) Netdnses() NetdnsInformer {
	return &netdnsInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
