// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteKdoctoragentParams creates a new DeleteKdoctoragentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteKdoctoragentParams() *DeleteKdoctoragentParams {
	return &DeleteKdoctoragentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteKdoctoragentParamsWithTimeout creates a new DeleteKdoctoragentParams object
// with the ability to set a timeout on a request.
func NewDeleteKdoctoragentParamsWithTimeout(timeout time.Duration) *DeleteKdoctoragentParams {
	return &DeleteKdoctoragentParams{
		timeout: timeout,
	}
}

// NewDeleteKdoctoragentParamsWithContext creates a new DeleteKdoctoragentParams object
// with the ability to set a context for a request.
func NewDeleteKdoctoragentParamsWithContext(ctx context.Context) *DeleteKdoctoragentParams {
	return &DeleteKdoctoragentParams{
		Context: ctx,
	}
}

// NewDeleteKdoctoragentParamsWithHTTPClient creates a new DeleteKdoctoragentParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteKdoctoragentParamsWithHTTPClient(client *http.Client) *DeleteKdoctoragentParams {
	return &DeleteKdoctoragentParams{
		HTTPClient: client,
	}
}

/*
DeleteKdoctoragentParams contains all the parameters to send to the API endpoint

	for the delete kdoctoragent operation.

	Typically these are written to a http.Request.
*/
type DeleteKdoctoragentParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete kdoctoragent params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteKdoctoragentParams) WithDefaults() *DeleteKdoctoragentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete kdoctoragent params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteKdoctoragentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete kdoctoragent params
func (o *DeleteKdoctoragentParams) WithTimeout(timeout time.Duration) *DeleteKdoctoragentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete kdoctoragent params
func (o *DeleteKdoctoragentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete kdoctoragent params
func (o *DeleteKdoctoragentParams) WithContext(ctx context.Context) *DeleteKdoctoragentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete kdoctoragent params
func (o *DeleteKdoctoragentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete kdoctoragent params
func (o *DeleteKdoctoragentParams) WithHTTPClient(client *http.Client) *DeleteKdoctoragentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete kdoctoragent params
func (o *DeleteKdoctoragentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteKdoctoragentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
