// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// HeadKdoctoragentReader is a Reader for the HeadKdoctoragent structure.
type HeadKdoctoragentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HeadKdoctoragentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewHeadKdoctoragentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewHeadKdoctoragentInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewHeadKdoctoragentOK creates a HeadKdoctoragentOK with default headers values
func NewHeadKdoctoragentOK() *HeadKdoctoragentOK {
	return &HeadKdoctoragentOK{}
}

/*
HeadKdoctoragentOK describes a response with status code 200, with default header values.

Success
*/
type HeadKdoctoragentOK struct {
}

// IsSuccess returns true when this head kdoctoragent o k response has a 2xx status code
func (o *HeadKdoctoragentOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this head kdoctoragent o k response has a 3xx status code
func (o *HeadKdoctoragentOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this head kdoctoragent o k response has a 4xx status code
func (o *HeadKdoctoragentOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this head kdoctoragent o k response has a 5xx status code
func (o *HeadKdoctoragentOK) IsServerError() bool {
	return false
}

// IsCode returns true when this head kdoctoragent o k response a status code equal to that given
func (o *HeadKdoctoragentOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the head kdoctoragent o k response
func (o *HeadKdoctoragentOK) Code() int {
	return 200
}

func (o *HeadKdoctoragentOK) Error() string {
	return fmt.Sprintf("[HEAD /kdoctoragent][%d] headKdoctoragentOK ", 200)
}

func (o *HeadKdoctoragentOK) String() string {
	return fmt.Sprintf("[HEAD /kdoctoragent][%d] headKdoctoragentOK ", 200)
}

func (o *HeadKdoctoragentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewHeadKdoctoragentInternalServerError creates a HeadKdoctoragentInternalServerError with default headers values
func NewHeadKdoctoragentInternalServerError() *HeadKdoctoragentInternalServerError {
	return &HeadKdoctoragentInternalServerError{}
}

/*
HeadKdoctoragentInternalServerError describes a response with status code 500, with default header values.

Failed
*/
type HeadKdoctoragentInternalServerError struct {
}

// IsSuccess returns true when this head kdoctoragent internal server error response has a 2xx status code
func (o *HeadKdoctoragentInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this head kdoctoragent internal server error response has a 3xx status code
func (o *HeadKdoctoragentInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this head kdoctoragent internal server error response has a 4xx status code
func (o *HeadKdoctoragentInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this head kdoctoragent internal server error response has a 5xx status code
func (o *HeadKdoctoragentInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this head kdoctoragent internal server error response a status code equal to that given
func (o *HeadKdoctoragentInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the head kdoctoragent internal server error response
func (o *HeadKdoctoragentInternalServerError) Code() int {
	return 500
}

func (o *HeadKdoctoragentInternalServerError) Error() string {
	return fmt.Sprintf("[HEAD /kdoctoragent][%d] headKdoctoragentInternalServerError ", 500)
}

func (o *HeadKdoctoragentInternalServerError) String() string {
	return fmt.Sprintf("[HEAD /kdoctoragent][%d] headKdoctoragentInternalServerError ", 500)
}

func (o *HeadKdoctoragentInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
