// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// OptionsKdoctoragentReader is a Reader for the OptionsKdoctoragent structure.
type OptionsKdoctoragentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OptionsKdoctoragentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOptionsKdoctoragentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewOptionsKdoctoragentInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewOptionsKdoctoragentOK creates a OptionsKdoctoragentOK with default headers values
func NewOptionsKdoctoragentOK() *OptionsKdoctoragentOK {
	return &OptionsKdoctoragentOK{}
}

/*
OptionsKdoctoragentOK describes a response with status code 200, with default header values.

Success
*/
type OptionsKdoctoragentOK struct {
}

// IsSuccess returns true when this options kdoctoragent o k response has a 2xx status code
func (o *OptionsKdoctoragentOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this options kdoctoragent o k response has a 3xx status code
func (o *OptionsKdoctoragentOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this options kdoctoragent o k response has a 4xx status code
func (o *OptionsKdoctoragentOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this options kdoctoragent o k response has a 5xx status code
func (o *OptionsKdoctoragentOK) IsServerError() bool {
	return false
}

// IsCode returns true when this options kdoctoragent o k response a status code equal to that given
func (o *OptionsKdoctoragentOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the options kdoctoragent o k response
func (o *OptionsKdoctoragentOK) Code() int {
	return 200
}

func (o *OptionsKdoctoragentOK) Error() string {
	return fmt.Sprintf("[OPTIONS /kdoctoragent][%d] optionsKdoctoragentOK ", 200)
}

func (o *OptionsKdoctoragentOK) String() string {
	return fmt.Sprintf("[OPTIONS /kdoctoragent][%d] optionsKdoctoragentOK ", 200)
}

func (o *OptionsKdoctoragentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewOptionsKdoctoragentInternalServerError creates a OptionsKdoctoragentInternalServerError with default headers values
func NewOptionsKdoctoragentInternalServerError() *OptionsKdoctoragentInternalServerError {
	return &OptionsKdoctoragentInternalServerError{}
}

/*
OptionsKdoctoragentInternalServerError describes a response with status code 500, with default header values.

Failed
*/
type OptionsKdoctoragentInternalServerError struct {
}

// IsSuccess returns true when this options kdoctoragent internal server error response has a 2xx status code
func (o *OptionsKdoctoragentInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this options kdoctoragent internal server error response has a 3xx status code
func (o *OptionsKdoctoragentInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this options kdoctoragent internal server error response has a 4xx status code
func (o *OptionsKdoctoragentInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this options kdoctoragent internal server error response has a 5xx status code
func (o *OptionsKdoctoragentInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this options kdoctoragent internal server error response a status code equal to that given
func (o *OptionsKdoctoragentInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the options kdoctoragent internal server error response
func (o *OptionsKdoctoragentInternalServerError) Code() int {
	return 500
}

func (o *OptionsKdoctoragentInternalServerError) Error() string {
	return fmt.Sprintf("[OPTIONS /kdoctoragent][%d] optionsKdoctoragentInternalServerError ", 500)
}

func (o *OptionsKdoctoragentInternalServerError) String() string {
	return fmt.Sprintf("[OPTIONS /kdoctoragent][%d] optionsKdoctoragentInternalServerError ", 500)
}

func (o *OptionsKdoctoragentInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
