// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kdoctor-io/kdoctor/api/v1/agentServer/models"
)

// PatchKdoctoragentReader is a Reader for the PatchKdoctoragent structure.
type PatchKdoctoragentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchKdoctoragentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchKdoctoragentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPatchKdoctoragentOK creates a PatchKdoctoragentOK with default headers values
func NewPatchKdoctoragentOK() *PatchKdoctoragentOK {
	return &PatchKdoctoragentOK{}
}

/*
PatchKdoctoragentOK describes a response with status code 200, with default header values.

Success
*/
type PatchKdoctoragentOK struct {
	Payload *models.EchoRes
}

// IsSuccess returns true when this patch kdoctoragent o k response has a 2xx status code
func (o *PatchKdoctoragentOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this patch kdoctoragent o k response has a 3xx status code
func (o *PatchKdoctoragentOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch kdoctoragent o k response has a 4xx status code
func (o *PatchKdoctoragentOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch kdoctoragent o k response has a 5xx status code
func (o *PatchKdoctoragentOK) IsServerError() bool {
	return false
}

// IsCode returns true when this patch kdoctoragent o k response a status code equal to that given
func (o *PatchKdoctoragentOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the patch kdoctoragent o k response
func (o *PatchKdoctoragentOK) Code() int {
	return 200
}

func (o *PatchKdoctoragentOK) Error() string {
	return fmt.Sprintf("[PATCH /kdoctoragent][%d] patchKdoctoragentOK  %+v", 200, o.Payload)
}

func (o *PatchKdoctoragentOK) String() string {
	return fmt.Sprintf("[PATCH /kdoctoragent][%d] patchKdoctoragentOK  %+v", 200, o.Payload)
}

func (o *PatchKdoctoragentOK) GetPayload() *models.EchoRes {
	return o.Payload
}

func (o *PatchKdoctoragentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EchoRes)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
