// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kdoctor-io/kdoctor/api/v1/agentServer/models"
)

// PostReader is a Reader for the Post structure.
type PostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewPostInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostOK creates a PostOK with default headers values
func NewPostOK() *PostOK {
	return &PostOK{}
}

/*
PostOK describes a response with status code 200, with default header values.

Success
*/
type PostOK struct {
	Payload *models.EchoRes
}

// IsSuccess returns true when this post o k response has a 2xx status code
func (o *PostOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post o k response has a 3xx status code
func (o *PostOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post o k response has a 4xx status code
func (o *PostOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post o k response has a 5xx status code
func (o *PostOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post o k response a status code equal to that given
func (o *PostOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post o k response
func (o *PostOK) Code() int {
	return 200
}

func (o *PostOK) Error() string {
	return fmt.Sprintf("[POST /][%d] postOK  %+v", 200, o.Payload)
}

func (o *PostOK) String() string {
	return fmt.Sprintf("[POST /][%d] postOK  %+v", 200, o.Payload)
}

func (o *PostOK) GetPayload() *models.EchoRes {
	return o.Payload
}

func (o *PostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EchoRes)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostInternalServerError creates a PostInternalServerError with default headers values
func NewPostInternalServerError() *PostInternalServerError {
	return &PostInternalServerError{}
}

/*
PostInternalServerError describes a response with status code 500, with default header values.

Failed
*/
type PostInternalServerError struct {
}

// IsSuccess returns true when this post internal server error response has a 2xx status code
func (o *PostInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post internal server error response has a 3xx status code
func (o *PostInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post internal server error response has a 4xx status code
func (o *PostInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post internal server error response has a 5xx status code
func (o *PostInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post internal server error response a status code equal to that given
func (o *PostInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post internal server error response
func (o *PostInternalServerError) Code() int {
	return 500
}

func (o *PostInternalServerError) Error() string {
	return fmt.Sprintf("[POST /][%d] postInternalServerError ", 500)
}

func (o *PostInternalServerError) String() string {
	return fmt.Sprintf("[POST /][%d] postInternalServerError ", 500)
}

func (o *PostInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
