// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/kdoctor-io/kdoctor/api/v1/agentServer/models"
)

// NewPostParams creates a new PostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostParams() *PostParams {
	return &PostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostParamsWithTimeout creates a new PostParams object
// with the ability to set a timeout on a request.
func NewPostParamsWithTimeout(timeout time.Duration) *PostParams {
	return &PostParams{
		timeout: timeout,
	}
}

// NewPostParamsWithContext creates a new PostParams object
// with the ability to set a context for a request.
func NewPostParamsWithContext(ctx context.Context) *PostParams {
	return &PostParams{
		Context: ctx,
	}
}

// NewPostParamsWithHTTPClient creates a new PostParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostParamsWithHTTPClient(client *http.Client) *PostParams {
	return &PostParams{
		HTTPClient: client,
	}
}

/*
PostParams contains all the parameters to send to the API endpoint

	for the post operation.

	Typically these are written to a http.Request.
*/
type PostParams struct {

	/* Delay.

	   delay some second return response
	*/
	Delay *int64

	/* Task.

	   task name
	*/
	Task *string

	// TestArgs.
	TestArgs *models.EchoBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostParams) WithDefaults() *PostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post params
func (o *PostParams) WithTimeout(timeout time.Duration) *PostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post params
func (o *PostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post params
func (o *PostParams) WithContext(ctx context.Context) *PostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post params
func (o *PostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post params
func (o *PostParams) WithHTTPClient(client *http.Client) *PostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post params
func (o *PostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDelay adds the delay to the post params
func (o *PostParams) WithDelay(delay *int64) *PostParams {
	o.SetDelay(delay)
	return o
}

// SetDelay adds the delay to the post params
func (o *PostParams) SetDelay(delay *int64) {
	o.Delay = delay
}

// WithTask adds the task to the post params
func (o *PostParams) WithTask(task *string) *PostParams {
	o.SetTask(task)
	return o
}

// SetTask adds the task to the post params
func (o *PostParams) SetTask(task *string) {
	o.Task = task
}

// WithTestArgs adds the testArgs to the post params
func (o *PostParams) WithTestArgs(testArgs *models.EchoBody) *PostParams {
	o.SetTestArgs(testArgs)
	return o
}

// SetTestArgs adds the testArgs to the post params
func (o *PostParams) SetTestArgs(testArgs *models.EchoBody) {
	o.TestArgs = testArgs
}

// WriteToRequest writes these params to a swagger request
func (o *PostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Delay != nil {

		// query param delay
		var qrDelay int64

		if o.Delay != nil {
			qrDelay = *o.Delay
		}
		qDelay := swag.FormatInt64(qrDelay)
		if qDelay != "" {

			if err := r.SetQueryParam("delay", qDelay); err != nil {
				return err
			}
		}
	}

	if o.Task != nil {

		// query param task
		var qrTask string

		if o.Task != nil {
			qrTask = *o.Task
		}
		qTask := qrTask
		if qTask != "" {

			if err := r.SetQueryParam("task", qTask); err != nil {
				return err
			}
		}
	}
	if o.TestArgs != nil {
		if err := r.SetBodyParam(o.TestArgs); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
