// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kdoctor-io/kdoctor/api/v1/agentServer/models"
)

// PostKdoctoragentReader is a Reader for the PostKdoctoragent structure.
type PostKdoctoragentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostKdoctoragentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostKdoctoragentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewPostKdoctoragentInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostKdoctoragentOK creates a PostKdoctoragentOK with default headers values
func NewPostKdoctoragentOK() *PostKdoctoragentOK {
	return &PostKdoctoragentOK{}
}

/*
PostKdoctoragentOK describes a response with status code 200, with default header values.

Success
*/
type PostKdoctoragentOK struct {
	Payload *models.EchoRes
}

// IsSuccess returns true when this post kdoctoragent o k response has a 2xx status code
func (o *PostKdoctoragentOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post kdoctoragent o k response has a 3xx status code
func (o *PostKdoctoragentOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post kdoctoragent o k response has a 4xx status code
func (o *PostKdoctoragentOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post kdoctoragent o k response has a 5xx status code
func (o *PostKdoctoragentOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post kdoctoragent o k response a status code equal to that given
func (o *PostKdoctoragentOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post kdoctoragent o k response
func (o *PostKdoctoragentOK) Code() int {
	return 200
}

func (o *PostKdoctoragentOK) Error() string {
	return fmt.Sprintf("[POST /kdoctoragent][%d] postKdoctoragentOK  %+v", 200, o.Payload)
}

func (o *PostKdoctoragentOK) String() string {
	return fmt.Sprintf("[POST /kdoctoragent][%d] postKdoctoragentOK  %+v", 200, o.Payload)
}

func (o *PostKdoctoragentOK) GetPayload() *models.EchoRes {
	return o.Payload
}

func (o *PostKdoctoragentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EchoRes)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostKdoctoragentInternalServerError creates a PostKdoctoragentInternalServerError with default headers values
func NewPostKdoctoragentInternalServerError() *PostKdoctoragentInternalServerError {
	return &PostKdoctoragentInternalServerError{}
}

/*
PostKdoctoragentInternalServerError describes a response with status code 500, with default header values.

Failed
*/
type PostKdoctoragentInternalServerError struct {
}

// IsSuccess returns true when this post kdoctoragent internal server error response has a 2xx status code
func (o *PostKdoctoragentInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post kdoctoragent internal server error response has a 3xx status code
func (o *PostKdoctoragentInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post kdoctoragent internal server error response has a 4xx status code
func (o *PostKdoctoragentInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post kdoctoragent internal server error response has a 5xx status code
func (o *PostKdoctoragentInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post kdoctoragent internal server error response a status code equal to that given
func (o *PostKdoctoragentInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post kdoctoragent internal server error response
func (o *PostKdoctoragentInternalServerError) Code() int {
	return 500
}

func (o *PostKdoctoragentInternalServerError) Error() string {
	return fmt.Sprintf("[POST /kdoctoragent][%d] postKdoctoragentInternalServerError ", 500)
}

func (o *PostKdoctoragentInternalServerError) String() string {
	return fmt.Sprintf("[POST /kdoctoragent][%d] postKdoctoragentInternalServerError ", 500)
}

func (o *PostKdoctoragentInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
