// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetKdoctoragentHandlerFunc turns a function with the right signature into a get kdoctoragent handler
type GetKdoctoragentHandlerFunc func(GetKdoctoragentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetKdoctoragentHandlerFunc) Handle(params GetKdoctoragentParams) middleware.Responder {
	return fn(params)
}

// GetKdoctoragentHandler interface for that can handle valid get kdoctoragent params
type GetKdoctoragentHandler interface {
	Handle(GetKdoctoragentParams) middleware.Responder
}

// NewGetKdoctoragent creates a new http.Handler for the get kdoctoragent operation
func NewGetKdoctoragent(ctx *middleware.Context, handler GetKdoctoragentHandler) *GetKdoctoragent {
	return &GetKdoctoragent{Context: ctx, Handler: handler}
}

/*
	GetKdoctoragent swagger:route GET /kdoctoragent echo getKdoctoragent

echo http request

echo http request
*/
type GetKdoctoragent struct {
	Context *middleware.Context
	Handler GetKdoctoragentHandler
}

func (o *GetKdoctoragent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetKdoctoragentParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
