// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetkdoctoragentHandlerFunc turns a function with the right signature into a get kdoctoragent handler
type GetkdoctoragentHandlerFunc func(GetkdoctoragentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetkdoctoragentHandlerFunc) Handle(params GetkdoctoragentParams) middleware.Responder {
	return fn(params)
}

// GetkdoctoragentHandler interface for that can handle valid get kdoctoragent params
type GetkdoctoragentHandler interface {
	Handle(GetkdoctoragentParams) middleware.Responder
}

// NewGetkdoctoragent creates a new http.Handler for the get kdoctoragent operation
func NewGetkdoctoragent(ctx *middleware.Context, handler GetkdoctoragentHandler) *Getkdoctoragent {
	return &Getkdoctoragent{Context: ctx, Handler: handler}
}

/*
	Getkdoctoragent swagger:route GET /kdoctoragent echo getkdoctoragent

echo http request

echo http request
*/
type Getkdoctoragent struct {
	Context *middleware.Context
	Handler GetkdoctoragentHandler
}

func (o *Getkdoctoragent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetkdoctoragentParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
