// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kdoctor-io/kdoctor/api/v1/agentServer/models"
)

// GetKdoctoragentOKCode is the HTTP code returned for type GetKdoctoragentOK
const GetKdoctoragentOKCode int = 200

/*
GetKdoctoragentOK Success

swagger:response getKdoctoragentOK
*/
type GetKdoctoragentOK struct {

	/*
	  In: Body
	*/
	Payload *models.EchoRes `json:"body,omitempty"`
}

// NewGetKdoctoragentOK creates GetKdoctoragentOK with default headers values
func NewGetKdoctoragentOK() *GetKdoctoragentOK {

	return &GetKdoctoragentOK{}
}

// WithPayload adds the payload to the get kdoctoragent o k response
func (o *GetKdoctoragentOK) WithPayload(payload *models.EchoRes) *GetKdoctoragentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get kdoctoragent o k response
func (o *GetKdoctoragentOK) SetPayload(payload *models.EchoRes) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetKdoctoragentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
