// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kdoctor-io/kdoctor/api/v1/agentServer/models"
)

// HeadKdoctoragentOKCode is the HTTP code returned for type HeadKdoctoragentOK
const HeadKdoctoragentOKCode int = 200

/*
HeadKdoctoragentOK Success

swagger:response headKdoctoragentOK
*/
type HeadKdoctoragentOK struct {

	/*
	  In: Body
	*/
	Payload *models.EchoRes `json:"body,omitempty"`
}

// NewHeadKdoctoragentOK creates HeadKdoctoragentOK with default headers values
func NewHeadKdoctoragentOK() *HeadKdoctoragentOK {

	return &HeadKdoctoragentOK{}
}

// WithPayload adds the payload to the head kdoctoragent o k response
func (o *HeadKdoctoragentOK) WithPayload(payload *models.EchoRes) *HeadKdoctoragentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the head kdoctoragent o k response
func (o *HeadKdoctoragentOK) SetPayload(payload *models.EchoRes) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *HeadKdoctoragentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
