// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// HeadOKCode is the HTTP code returned for type HeadOK
const HeadOKCode int = 200

/*
HeadOK Success

swagger:response headOK
*/
type HeadOK struct {
}

// NewHeadOK creates HeadOK with default headers values
func NewHeadOK() *HeadOK {

	return &HeadOK{}
}

// WriteResponse to the client
func (o *HeadOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// HeadInternalServerErrorCode is the HTTP code returned for type HeadInternalServerError
const HeadInternalServerErrorCode int = 500

/*
HeadInternalServerError Failed

swagger:response headInternalServerError
*/
type HeadInternalServerError struct {
}

// NewHeadInternalServerError creates HeadInternalServerError with default headers values
func NewHeadInternalServerError() *HeadInternalServerError {

	return &HeadInternalServerError{}
}

// WriteResponse to the client
func (o *HeadInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
