// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// HeadKdoctoragentOKCode is the HTTP code returned for type HeadKdoctoragentOK
const HeadKdoctoragentOKCode int = 200

/*
HeadKdoctoragentOK Success

swagger:response headKdoctoragentOK
*/
type HeadKdoctoragentOK struct {
}

// NewHeadKdoctoragentOK creates HeadKdoctoragentOK with default headers values
func NewHeadKdoctoragentOK() *HeadKdoctoragentOK {

	return &HeadKdoctoragentOK{}
}

// WriteResponse to the client
func (o *HeadKdoctoragentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// HeadKdoctoragentInternalServerErrorCode is the HTTP code returned for type HeadKdoctoragentInternalServerError
const HeadKdoctoragentInternalServerErrorCode int = 500

/*
HeadKdoctoragentInternalServerError Failed

swagger:response headKdoctoragentInternalServerError
*/
type HeadKdoctoragentInternalServerError struct {
}

// NewHeadKdoctoragentInternalServerError creates HeadKdoctoragentInternalServerError with default headers values
func NewHeadKdoctoragentInternalServerError() *HeadKdoctoragentInternalServerError {

	return &HeadKdoctoragentInternalServerError{}
}

// WriteResponse to the client
func (o *HeadKdoctoragentInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
