// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kdoctor-io/kdoctor/api/v1/agentServer/models"
)

// OptionsOKCode is the HTTP code returned for type OptionsOK
const OptionsOKCode int = 200

/*
OptionsOK Success

swagger:response optionsOK
*/
type OptionsOK struct {

	/*
	  In: Body
	*/
	Payload *models.EchoRes `json:"body,omitempty"`
}

// NewOptionsOK creates OptionsOK with default headers values
func NewOptionsOK() *OptionsOK {

	return &OptionsOK{}
}

// WithPayload adds the payload to the options o k response
func (o *OptionsOK) WithPayload(payload *models.EchoRes) *OptionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the options o k response
func (o *OptionsOK) SetPayload(payload *models.EchoRes) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *OptionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
