// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kdoctor-io/kdoctor/api/v1/agentServer/models"
)

// OptionsKdoctoragentOKCode is the HTTP code returned for type OptionsKdoctoragentOK
const OptionsKdoctoragentOKCode int = 200

/*
OptionsKdoctoragentOK Success

swagger:response optionsKdoctoragentOK
*/
type OptionsKdoctoragentOK struct {

	/*
	  In: Body
	*/
	Payload *models.EchoRes `json:"body,omitempty"`
}

// NewOptionsKdoctoragentOK creates OptionsKdoctoragentOK with default headers values
func NewOptionsKdoctoragentOK() *OptionsKdoctoragentOK {

	return &OptionsKdoctoragentOK{}
}

// WithPayload adds the payload to the options kdoctoragent o k response
func (o *OptionsKdoctoragentOK) WithPayload(payload *models.EchoRes) *OptionsKdoctoragentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the options kdoctoragent o k response
func (o *OptionsKdoctoragentOK) SetPayload(payload *models.EchoRes) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *OptionsKdoctoragentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
