// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PatchKdoctoragentOKCode is the HTTP code returned for type PatchKdoctoragentOK
const PatchKdoctoragentOKCode int = 200

/*
PatchKdoctoragentOK Success

swagger:response patchKdoctoragentOK
*/
type PatchKdoctoragentOK struct {
}

// NewPatchKdoctoragentOK creates PatchKdoctoragentOK with default headers values
func NewPatchKdoctoragentOK() *PatchKdoctoragentOK {

	return &PatchKdoctoragentOK{}
}

// WriteResponse to the client
func (o *PatchKdoctoragentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PatchKdoctoragentInternalServerErrorCode is the HTTP code returned for type PatchKdoctoragentInternalServerError
const PatchKdoctoragentInternalServerErrorCode int = 500

/*
PatchKdoctoragentInternalServerError Failed

swagger:response patchKdoctoragentInternalServerError
*/
type PatchKdoctoragentInternalServerError struct {
}

// NewPatchKdoctoragentInternalServerError creates PatchKdoctoragentInternalServerError with default headers values
func NewPatchKdoctoragentInternalServerError() *PatchKdoctoragentInternalServerError {

	return &PatchKdoctoragentInternalServerError{}
}

// WriteResponse to the client
func (o *PatchKdoctoragentInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
