// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kdoctor-io/kdoctor/api/v1/agentServer/models"
)

// PatchKdoctoragentOKCode is the HTTP code returned for type PatchKdoctoragentOK
const PatchKdoctoragentOKCode int = 200

/*
PatchKdoctoragentOK Success

swagger:response patchKdoctoragentOK
*/
type PatchKdoctoragentOK struct {

	/*
	  In: Body
	*/
	Payload *models.EchoRes `json:"body,omitempty"`
}

// NewPatchKdoctoragentOK creates PatchKdoctoragentOK with default headers values
func NewPatchKdoctoragentOK() *PatchKdoctoragentOK {

	return &PatchKdoctoragentOK{}
}

// WithPayload adds the payload to the patch kdoctoragent o k response
func (o *PatchKdoctoragentOK) WithPayload(payload *models.EchoRes) *PatchKdoctoragentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch kdoctoragent o k response
func (o *PatchKdoctoragentOK) SetPayload(payload *models.EchoRes) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchKdoctoragentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
