// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PatchOKCode is the HTTP code returned for type PatchOK
const PatchOKCode int = 200

/*
PatchOK Success

swagger:response patchOK
*/
type PatchOK struct {
}

// NewPatchOK creates PatchOK with default headers values
func NewPatchOK() *PatchOK {

	return &PatchOK{}
}

// WriteResponse to the client
func (o *PatchOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PatchInternalServerErrorCode is the HTTP code returned for type PatchInternalServerError
const PatchInternalServerErrorCode int = 500

/*
PatchInternalServerError Failed

swagger:response patchInternalServerError
*/
type PatchInternalServerError struct {
}

// NewPatchInternalServerError creates PatchInternalServerError with default headers values
func NewPatchInternalServerError() *PatchInternalServerError {

	return &PatchInternalServerError{}
}

// WriteResponse to the client
func (o *PatchInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
