// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kdoctor-io/kdoctor/api/v1/agentServer/models"
)

// PostOKCode is the HTTP code returned for type PostOK
const PostOKCode int = 200

/*
PostOK Success

swagger:response postOK
*/
type PostOK struct {

	/*
	  In: Body
	*/
	Payload *models.EchoRes `json:"body,omitempty"`
}

// NewPostOK creates PostOK with default headers values
func NewPostOK() *PostOK {

	return &PostOK{}
}

// WithPayload adds the payload to the post o k response
func (o *PostOK) WithPayload(payload *models.EchoRes) *PostOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post o k response
func (o *PostOK) SetPayload(payload *models.EchoRes) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostInternalServerErrorCode is the HTTP code returned for type PostInternalServerError
const PostInternalServerErrorCode int = 500

/*
PostInternalServerError Failed

swagger:response postInternalServerError
*/
type PostInternalServerError struct {
}

// NewPostInternalServerError creates PostInternalServerError with default headers values
func NewPostInternalServerError() *PostInternalServerError {

	return &PostInternalServerError{}
}

// WriteResponse to the client
func (o *PostInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
