// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostOKCode is the HTTP code returned for type PostOK
const PostOKCode int = 200

/*
PostOK Success

swagger:response postOK
*/
type PostOK struct {
}

// NewPostOK creates PostOK with default headers values
func NewPostOK() *PostOK {

	return &PostOK{}
}

// WriteResponse to the client
func (o *PostOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostInternalServerErrorCode is the HTTP code returned for type PostInternalServerError
const PostInternalServerErrorCode int = 500

/*
PostInternalServerError Failed

swagger:response postInternalServerError
*/
type PostInternalServerError struct {
}

// NewPostInternalServerError creates PostInternalServerError with default headers values
func NewPostInternalServerError() *PostInternalServerError {

	return &PostInternalServerError{}
}

// WriteResponse to the client
func (o *PostInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
