// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutKdoctoragentOKCode is the HTTP code returned for type PutKdoctoragentOK
const PutKdoctoragentOKCode int = 200

/*
PutKdoctoragentOK Success

swagger:response putKdoctoragentOK
*/
type PutKdoctoragentOK struct {
}

// NewPutKdoctoragentOK creates PutKdoctoragentOK with default headers values
func NewPutKdoctoragentOK() *PutKdoctoragentOK {

	return &PutKdoctoragentOK{}
}

// WriteResponse to the client
func (o *PutKdoctoragentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PutKdoctoragentInternalServerErrorCode is the HTTP code returned for type PutKdoctoragentInternalServerError
const PutKdoctoragentInternalServerErrorCode int = 500

/*
PutKdoctoragentInternalServerError Failed

swagger:response putKdoctoragentInternalServerError
*/
type PutKdoctoragentInternalServerError struct {
}

// NewPutKdoctoragentInternalServerError creates PutKdoctoragentInternalServerError with default headers values
func NewPutKdoctoragentInternalServerError() *PutKdoctoragentInternalServerError {

	return &PutKdoctoragentInternalServerError{}
}

// WriteResponse to the client
func (o *PutKdoctoragentInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
