// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutOKCode is the HTTP code returned for type PutOK
const PutOKCode int = 200

/*
PutOK Success

swagger:response putOK
*/
type PutOK struct {
}

// NewPutOK creates PutOK with default headers values
func NewPutOK() *PutOK {

	return &PutOK{}
}

// WriteResponse to the client
func (o *PutOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PutInternalServerErrorCode is the HTTP code returned for type PutInternalServerError
const PutInternalServerErrorCode int = 500

/*
PutInternalServerError Failed

swagger:response putInternalServerError
*/
type PutInternalServerError struct {
}

// NewPutInternalServerError creates PutInternalServerError with default headers values
func NewPutInternalServerError() *PutInternalServerError {

	return &PutInternalServerError{}
}

// WriteResponse to the client
func (o *PutInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
