// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutKdoctoragentHandlerFunc turns a function with the right signature into a put kdoctoragent handler
type PutKdoctoragentHandlerFunc func(PutKdoctoragentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutKdoctoragentHandlerFunc) Handle(params PutKdoctoragentParams) middleware.Responder {
	return fn(params)
}

// PutKdoctoragentHandler interface for that can handle valid put kdoctoragent params
type PutKdoctoragentHandler interface {
	Handle(PutKdoctoragentParams) middleware.Responder
}

// NewPutKdoctoragent creates a new http.Handler for the put kdoctoragent operation
func NewPutKdoctoragent(ctx *middleware.Context, handler PutKdoctoragentHandler) *PutKdoctoragent {
	return &PutKdoctoragent{Context: ctx, Handler: handler}
}

/*
	PutKdoctoragent swagger:route PUT /kdoctoragent echo putKdoctoragent

echo http request

echo http request
*/
type PutKdoctoragent struct {
	Context *middleware.Context
	Handler PutKdoctoragentHandler
}

func (o *PutKdoctoragent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutKdoctoragentParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
