// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/kdoctor-io/kdoctor/pkg/k8s/apis/kdoctor.io/v1beta1"
	scheme "github.com/kdoctor-io/kdoctor/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AppHttpHealthiesGetter has a method to return a AppHttpHealthyInterface.
// A group's client should implement this interface.
type AppHttpHealthiesGetter interface {
	AppHttpHealthies() AppHttpHealthyInterface
}

// AppHttpHealthyInterface has methods to work with AppHttpHealthy resources.
type AppHttpHealthyInterface interface {
	Create(ctx context.Context, appHttpHealthy *v1beta1.AppHttpHealthy, opts v1.CreateOptions) (*v1beta1.AppHttpHealthy, error)
	Update(ctx context.Context, appHttpHealthy *v1beta1.AppHttpHealthy, opts v1.UpdateOptions) (*v1beta1.AppHttpHealthy, error)
	UpdateStatus(ctx context.Context, appHttpHealthy *v1beta1.AppHttpHealthy, opts v1.UpdateOptions) (*v1beta1.AppHttpHealthy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.AppHttpHealthy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.AppHttpHealthyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.AppHttpHealthy, err error)
	AppHttpHealthyExpansion
}

// appHttpHealthies implements AppHttpHealthyInterface
type appHttpHealthies struct {
	client rest.Interface
}

// newAppHttpHealthies returns a AppHttpHealthies
func newAppHttpHealthies(c *KdoctorV1beta1Client) *appHttpHealthies {
	return &appHttpHealthies{
		client: c.RESTClient(),
	}
}

// Get takes name of the appHttpHealthy, and returns the corresponding appHttpHealthy object, and an error if there is any.
func (c *appHttpHealthies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.AppHttpHealthy, err error) {
	result = &v1beta1.AppHttpHealthy{}
	err = c.client.Get().
		Resource("apphttphealthies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AppHttpHealthies that match those selectors.
func (c *appHttpHealthies) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.AppHttpHealthyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.AppHttpHealthyList{}
	err = c.client.Get().
		Resource("apphttphealthies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested appHttpHealthies.
func (c *appHttpHealthies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("apphttphealthies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a appHttpHealthy and creates it.  Returns the server's representation of the appHttpHealthy, and an error, if there is any.
func (c *appHttpHealthies) Create(ctx context.Context, appHttpHealthy *v1beta1.AppHttpHealthy, opts v1.CreateOptions) (result *v1beta1.AppHttpHealthy, err error) {
	result = &v1beta1.AppHttpHealthy{}
	err = c.client.Post().
		Resource("apphttphealthies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(appHttpHealthy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a appHttpHealthy and updates it. Returns the server's representation of the appHttpHealthy, and an error, if there is any.
func (c *appHttpHealthies) Update(ctx context.Context, appHttpHealthy *v1beta1.AppHttpHealthy, opts v1.UpdateOptions) (result *v1beta1.AppHttpHealthy, err error) {
	result = &v1beta1.AppHttpHealthy{}
	err = c.client.Put().
		Resource("apphttphealthies").
		Name(appHttpHealthy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(appHttpHealthy).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *appHttpHealthies) UpdateStatus(ctx context.Context, appHttpHealthy *v1beta1.AppHttpHealthy, opts v1.UpdateOptions) (result *v1beta1.AppHttpHealthy, err error) {
	result = &v1beta1.AppHttpHealthy{}
	err = c.client.Put().
		Resource("apphttphealthies").
		Name(appHttpHealthy.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(appHttpHealthy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the appHttpHealthy and deletes it. Returns an error if one occurs.
func (c *appHttpHealthies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("apphttphealthies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *appHttpHealthies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("apphttphealthies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched appHttpHealthy.
func (c *appHttpHealthies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.AppHttpHealthy, err error) {
	result = &v1beta1.AppHttpHealthy{}
	err = c.client.Patch(pt).
		Resource("apphttphealthies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
