// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

type HttpAppHealthyExpansion interface{}

type NetReachHealthyExpansion interface{}

type NetdnsExpansion interface{}
