// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

type AppHttpHealthyExpansion interface{}

type NetReachExpansion interface{}

type NetdnsExpansion interface{}
