// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/kdoctor-io/kdoctor/pkg/k8s/apis/kdoctor.io/v1beta1"
	scheme "github.com/kdoctor-io/kdoctor/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HttpAppHealthiesGetter has a method to return a HttpAppHealthyInterface.
// A group's client should implement this interface.
type HttpAppHealthiesGetter interface {
	HttpAppHealthies() HttpAppHealthyInterface
}

// HttpAppHealthyInterface has methods to work with HttpAppHealthy resources.
type HttpAppHealthyInterface interface {
	Create(ctx context.Context, httpAppHealthy *v1beta1.HttpAppHealthy, opts v1.CreateOptions) (*v1beta1.HttpAppHealthy, error)
	Update(ctx context.Context, httpAppHealthy *v1beta1.HttpAppHealthy, opts v1.UpdateOptions) (*v1beta1.HttpAppHealthy, error)
	UpdateStatus(ctx context.Context, httpAppHealthy *v1beta1.HttpAppHealthy, opts v1.UpdateOptions) (*v1beta1.HttpAppHealthy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.HttpAppHealthy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.HttpAppHealthyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.HttpAppHealthy, err error)
	HttpAppHealthyExpansion
}

// httpAppHealthies implements HttpAppHealthyInterface
type httpAppHealthies struct {
	client rest.Interface
}

// newHttpAppHealthies returns a HttpAppHealthies
func newHttpAppHealthies(c *KdoctorV1beta1Client) *httpAppHealthies {
	return &httpAppHealthies{
		client: c.RESTClient(),
	}
}

// Get takes name of the httpAppHealthy, and returns the corresponding httpAppHealthy object, and an error if there is any.
func (c *httpAppHealthies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.HttpAppHealthy, err error) {
	result = &v1beta1.HttpAppHealthy{}
	err = c.client.Get().
		Resource("httpapphealthies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of HttpAppHealthies that match those selectors.
func (c *httpAppHealthies) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.HttpAppHealthyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.HttpAppHealthyList{}
	err = c.client.Get().
		Resource("httpapphealthies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested httpAppHealthies.
func (c *httpAppHealthies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("httpapphealthies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a httpAppHealthy and creates it.  Returns the server's representation of the httpAppHealthy, and an error, if there is any.
func (c *httpAppHealthies) Create(ctx context.Context, httpAppHealthy *v1beta1.HttpAppHealthy, opts v1.CreateOptions) (result *v1beta1.HttpAppHealthy, err error) {
	result = &v1beta1.HttpAppHealthy{}
	err = c.client.Post().
		Resource("httpapphealthies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(httpAppHealthy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a httpAppHealthy and updates it. Returns the server's representation of the httpAppHealthy, and an error, if there is any.
func (c *httpAppHealthies) Update(ctx context.Context, httpAppHealthy *v1beta1.HttpAppHealthy, opts v1.UpdateOptions) (result *v1beta1.HttpAppHealthy, err error) {
	result = &v1beta1.HttpAppHealthy{}
	err = c.client.Put().
		Resource("httpapphealthies").
		Name(httpAppHealthy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(httpAppHealthy).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *httpAppHealthies) UpdateStatus(ctx context.Context, httpAppHealthy *v1beta1.HttpAppHealthy, opts v1.UpdateOptions) (result *v1beta1.HttpAppHealthy, err error) {
	result = &v1beta1.HttpAppHealthy{}
	err = c.client.Put().
		Resource("httpapphealthies").
		Name(httpAppHealthy.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(httpAppHealthy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the httpAppHealthy and deletes it. Returns an error if one occurs.
func (c *httpAppHealthies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("httpapphealthies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *httpAppHealthies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("httpapphealthies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched httpAppHealthy.
func (c *httpAppHealthies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.HttpAppHealthy, err error) {
	result = &v1beta1.HttpAppHealthy{}
	err = c.client.Patch(pt).
		Resource("httpapphealthies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
