// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/kdoctor-io/kdoctor/pkg/k8s/apis/kdoctor.io/v1beta1"
	scheme "github.com/kdoctor-io/kdoctor/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NetdnsesGetter has a method to return a NetdnsInterface.
// A group's client should implement this interface.
type NetdnsesGetter interface {
	Netdnses() NetdnsInterface
}

// NetdnsInterface has methods to work with Netdns resources.
type NetdnsInterface interface {
	Create(ctx context.Context, netdns *v1beta1.Netdns, opts v1.CreateOptions) (*v1beta1.Netdns, error)
	Update(ctx context.Context, netdns *v1beta1.Netdns, opts v1.UpdateOptions) (*v1beta1.Netdns, error)
	UpdateStatus(ctx context.Context, netdns *v1beta1.Netdns, opts v1.UpdateOptions) (*v1beta1.Netdns, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.Netdns, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.NetdnsList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.Netdns, err error)
	NetdnsExpansion
}

// netdnses implements NetdnsInterface
type netdnses struct {
	client rest.Interface
}

// newNetdnses returns a Netdnses
func newNetdnses(c *KdoctorV1beta1Client) *netdnses {
	return &netdnses{
		client: c.RESTClient(),
	}
}

// Get takes name of the netdns, and returns the corresponding netdns object, and an error if there is any.
func (c *netdnses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.Netdns, err error) {
	result = &v1beta1.Netdns{}
	err = c.client.Get().
		Resource("netdnses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Netdnses that match those selectors.
func (c *netdnses) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.NetdnsList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.NetdnsList{}
	err = c.client.Get().
		Resource("netdnses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested netdnses.
func (c *netdnses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("netdnses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a netdns and creates it.  Returns the server's representation of the netdns, and an error, if there is any.
func (c *netdnses) Create(ctx context.Context, netdns *v1beta1.Netdns, opts v1.CreateOptions) (result *v1beta1.Netdns, err error) {
	result = &v1beta1.Netdns{}
	err = c.client.Post().
		Resource("netdnses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(netdns).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a netdns and updates it. Returns the server's representation of the netdns, and an error, if there is any.
func (c *netdnses) Update(ctx context.Context, netdns *v1beta1.Netdns, opts v1.UpdateOptions) (result *v1beta1.Netdns, err error) {
	result = &v1beta1.Netdns{}
	err = c.client.Put().
		Resource("netdnses").
		Name(netdns.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(netdns).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *netdnses) UpdateStatus(ctx context.Context, netdns *v1beta1.Netdns, opts v1.UpdateOptions) (result *v1beta1.Netdns, err error) {
	result = &v1beta1.Netdns{}
	err = c.client.Put().
		Resource("netdnses").
		Name(netdns.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(netdns).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the netdns and deletes it. Returns an error if one occurs.
func (c *netdnses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("netdnses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *netdnses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("netdnses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched netdns.
func (c *netdnses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.Netdns, err error) {
	result = &v1beta1.Netdns{}
	err = c.client.Patch(pt).
		Resource("netdnses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
