// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/kdoctor-io/kdoctor/pkg/k8s/apis/kdoctor.io/v1beta1"
	scheme "github.com/kdoctor-io/kdoctor/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NetReachHealthiesGetter has a method to return a NetReachHealthyInterface.
// A group's client should implement this interface.
type NetReachHealthiesGetter interface {
	NetReachHealthies() NetReachHealthyInterface
}

// NetReachHealthyInterface has methods to work with NetReachHealthy resources.
type NetReachHealthyInterface interface {
	Create(ctx context.Context, netReachHealthy *v1beta1.NetReachHealthy, opts v1.CreateOptions) (*v1beta1.NetReachHealthy, error)
	Update(ctx context.Context, netReachHealthy *v1beta1.NetReachHealthy, opts v1.UpdateOptions) (*v1beta1.NetReachHealthy, error)
	UpdateStatus(ctx context.Context, netReachHealthy *v1beta1.NetReachHealthy, opts v1.UpdateOptions) (*v1beta1.NetReachHealthy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.NetReachHealthy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.NetReachHealthyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.NetReachHealthy, err error)
	NetReachHealthyExpansion
}

// netReachHealthies implements NetReachHealthyInterface
type netReachHealthies struct {
	client rest.Interface
}

// newNetReachHealthies returns a NetReachHealthies
func newNetReachHealthies(c *KdoctorV1beta1Client) *netReachHealthies {
	return &netReachHealthies{
		client: c.RESTClient(),
	}
}

// Get takes name of the netReachHealthy, and returns the corresponding netReachHealthy object, and an error if there is any.
func (c *netReachHealthies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.NetReachHealthy, err error) {
	result = &v1beta1.NetReachHealthy{}
	err = c.client.Get().
		Resource("netreachhealthies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NetReachHealthies that match those selectors.
func (c *netReachHealthies) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.NetReachHealthyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.NetReachHealthyList{}
	err = c.client.Get().
		Resource("netreachhealthies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested netReachHealthies.
func (c *netReachHealthies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("netreachhealthies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a netReachHealthy and creates it.  Returns the server's representation of the netReachHealthy, and an error, if there is any.
func (c *netReachHealthies) Create(ctx context.Context, netReachHealthy *v1beta1.NetReachHealthy, opts v1.CreateOptions) (result *v1beta1.NetReachHealthy, err error) {
	result = &v1beta1.NetReachHealthy{}
	err = c.client.Post().
		Resource("netreachhealthies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(netReachHealthy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a netReachHealthy and updates it. Returns the server's representation of the netReachHealthy, and an error, if there is any.
func (c *netReachHealthies) Update(ctx context.Context, netReachHealthy *v1beta1.NetReachHealthy, opts v1.UpdateOptions) (result *v1beta1.NetReachHealthy, err error) {
	result = &v1beta1.NetReachHealthy{}
	err = c.client.Put().
		Resource("netreachhealthies").
		Name(netReachHealthy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(netReachHealthy).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *netReachHealthies) UpdateStatus(ctx context.Context, netReachHealthy *v1beta1.NetReachHealthy, opts v1.UpdateOptions) (result *v1beta1.NetReachHealthy, err error) {
	result = &v1beta1.NetReachHealthy{}
	err = c.client.Put().
		Resource("netreachhealthies").
		Name(netReachHealthy.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(netReachHealthy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the netReachHealthy and deletes it. Returns an error if one occurs.
func (c *netReachHealthies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("netreachhealthies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *netReachHealthies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("netreachhealthies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched netReachHealthy.
func (c *netReachHealthies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.NetReachHealthy, err error) {
	result = &v1beta1.NetReachHealthy{}
	err = c.client.Patch(pt).
		Resource("netreachhealthies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
