// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/kdoctor-io/kdoctor/pkg/k8s/apis/kdoctor.io/v1beta1"
	scheme "github.com/kdoctor-io/kdoctor/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NetReachesGetter has a method to return a NetReachInterface.
// A group's client should implement this interface.
type NetReachesGetter interface {
	NetReaches() NetReachInterface
}

// NetReachInterface has methods to work with NetReach resources.
type NetReachInterface interface {
	Create(ctx context.Context, netReach *v1beta1.NetReach, opts v1.CreateOptions) (*v1beta1.NetReach, error)
	Update(ctx context.Context, netReach *v1beta1.NetReach, opts v1.UpdateOptions) (*v1beta1.NetReach, error)
	UpdateStatus(ctx context.Context, netReach *v1beta1.NetReach, opts v1.UpdateOptions) (*v1beta1.NetReach, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.NetReach, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.NetReachList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.NetReach, err error)
	NetReachExpansion
}

// netReaches implements NetReachInterface
type netReaches struct {
	client rest.Interface
}

// newNetReaches returns a NetReaches
func newNetReaches(c *KdoctorV1beta1Client) *netReaches {
	return &netReaches{
		client: c.RESTClient(),
	}
}

// Get takes name of the netReach, and returns the corresponding netReach object, and an error if there is any.
func (c *netReaches) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.NetReach, err error) {
	result = &v1beta1.NetReach{}
	err = c.client.Get().
		Resource("netreaches").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NetReaches that match those selectors.
func (c *netReaches) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.NetReachList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.NetReachList{}
	err = c.client.Get().
		Resource("netreaches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested netReaches.
func (c *netReaches) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("netreaches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a netReach and creates it.  Returns the server's representation of the netReach, and an error, if there is any.
func (c *netReaches) Create(ctx context.Context, netReach *v1beta1.NetReach, opts v1.CreateOptions) (result *v1beta1.NetReach, err error) {
	result = &v1beta1.NetReach{}
	err = c.client.Post().
		Resource("netreaches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(netReach).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a netReach and updates it. Returns the server's representation of the netReach, and an error, if there is any.
func (c *netReaches) Update(ctx context.Context, netReach *v1beta1.NetReach, opts v1.UpdateOptions) (result *v1beta1.NetReach, err error) {
	result = &v1beta1.NetReach{}
	err = c.client.Put().
		Resource("netreaches").
		Name(netReach.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(netReach).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *netReaches) UpdateStatus(ctx context.Context, netReach *v1beta1.NetReach, opts v1.UpdateOptions) (result *v1beta1.NetReach, err error) {
	result = &v1beta1.NetReach{}
	err = c.client.Put().
		Resource("netreaches").
		Name(netReach.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(netReach).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the netReach and deletes it. Returns an error if one occurs.
func (c *netReaches) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("netreaches").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *netReaches) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("netreaches").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched netReach.
func (c *netReaches) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.NetReach, err error) {
	result = &v1beta1.NetReach{}
	err = c.client.Patch(pt).
		Resource("netreaches").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
