// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/kdoctor-io/kdoctor/pkg/k8s/apis/kdoctor.io/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// AppHttpHealthyLister helps list AppHttpHealthies.
// All objects returned here must be treated as read-only.
type AppHttpHealthyLister interface {
	// List lists all AppHttpHealthies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.AppHttpHealthy, err error)
	// Get retrieves the AppHttpHealthy from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.AppHttpHealthy, error)
	AppHttpHealthyListerExpansion
}

// appHttpHealthyLister implements the AppHttpHealthyLister interface.
type appHttpHealthyLister struct {
	indexer cache.Indexer
}

// NewAppHttpHealthyLister returns a new AppHttpHealthyLister.
func NewAppHttpHealthyLister(indexer cache.Indexer) AppHttpHealthyLister {
	return &appHttpHealthyLister{indexer: indexer}
}

// List lists all AppHttpHealthies in the indexer.
func (s *appHttpHealthyLister) List(selector labels.Selector) (ret []*v1beta1.AppHttpHealthy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.AppHttpHealthy))
	})
	return ret, err
}

// Get retrieves the AppHttpHealthy from the index for a given name.
func (s *appHttpHealthyLister) Get(name string) (*v1beta1.AppHttpHealthy, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("apphttphealthy"), name)
	}
	return obj.(*v1beta1.AppHttpHealthy), nil
}
