// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// HttpAppHealthyListerExpansion allows custom methods to be added to
// HttpAppHealthyLister.
type HttpAppHealthyListerExpansion interface{}

// NetReachHealthyListerExpansion allows custom methods to be added to
// NetReachHealthyLister.
type NetReachHealthyListerExpansion interface{}

// NetdnsListerExpansion allows custom methods to be added to
// NetdnsLister.
type NetdnsListerExpansion interface{}
