// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// AppHttpHealthyListerExpansion allows custom methods to be added to
// AppHttpHealthyLister.
type AppHttpHealthyListerExpansion interface{}

// NetReachListerExpansion allows custom methods to be added to
// NetReachLister.
type NetReachListerExpansion interface{}

// NetdnsListerExpansion allows custom methods to be added to
// NetdnsLister.
type NetdnsListerExpansion interface{}
