// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/kdoctor-io/kdoctor/pkg/k8s/apis/kdoctor.io/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// HttpAppHealthyLister helps list HttpAppHealthies.
// All objects returned here must be treated as read-only.
type HttpAppHealthyLister interface {
	// List lists all HttpAppHealthies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.HttpAppHealthy, err error)
	// Get retrieves the HttpAppHealthy from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.HttpAppHealthy, error)
	HttpAppHealthyListerExpansion
}

// httpAppHealthyLister implements the HttpAppHealthyLister interface.
type httpAppHealthyLister struct {
	indexer cache.Indexer
}

// NewHttpAppHealthyLister returns a new HttpAppHealthyLister.
func NewHttpAppHealthyLister(indexer cache.Indexer) HttpAppHealthyLister {
	return &httpAppHealthyLister{indexer: indexer}
}

// List lists all HttpAppHealthies in the indexer.
func (s *httpAppHealthyLister) List(selector labels.Selector) (ret []*v1beta1.HttpAppHealthy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.HttpAppHealthy))
	})
	return ret, err
}

// Get retrieves the HttpAppHealthy from the index for a given name.
func (s *httpAppHealthyLister) Get(name string) (*v1beta1.HttpAppHealthy, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("httpapphealthy"), name)
	}
	return obj.(*v1beta1.HttpAppHealthy), nil
}
