// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/kdoctor-io/kdoctor/pkg/k8s/apis/kdoctor.io/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// NetdnsLister helps list Netdnses.
// All objects returned here must be treated as read-only.
type NetdnsLister interface {
	// List lists all Netdnses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.Netdns, err error)
	// Get retrieves the Netdns from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.Netdns, error)
	NetdnsListerExpansion
}

// netdnsLister implements the NetdnsLister interface.
type netdnsLister struct {
	indexer cache.Indexer
}

// NewNetdnsLister returns a new NetdnsLister.
func NewNetdnsLister(indexer cache.Indexer) NetdnsLister {
	return &netdnsLister{indexer: indexer}
}

// List lists all Netdnses in the indexer.
func (s *netdnsLister) List(selector labels.Selector) (ret []*v1beta1.Netdns, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.Netdns))
	})
	return ret, err
}

// Get retrieves the Netdns from the index for a given name.
func (s *netdnsLister) Get(name string) (*v1beta1.Netdns, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("netdns"), name)
	}
	return obj.(*v1beta1.Netdns), nil
}
