// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/kdoctor-io/kdoctor/pkg/k8s/apis/kdoctor.io/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// NetReachHealthyLister helps list NetReachHealthies.
// All objects returned here must be treated as read-only.
type NetReachHealthyLister interface {
	// List lists all NetReachHealthies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.NetReachHealthy, err error)
	// Get retrieves the NetReachHealthy from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.NetReachHealthy, error)
	NetReachHealthyListerExpansion
}

// netReachHealthyLister implements the NetReachHealthyLister interface.
type netReachHealthyLister struct {
	indexer cache.Indexer
}

// NewNetReachHealthyLister returns a new NetReachHealthyLister.
func NewNetReachHealthyLister(indexer cache.Indexer) NetReachHealthyLister {
	return &netReachHealthyLister{indexer: indexer}
}

// List lists all NetReachHealthies in the indexer.
func (s *netReachHealthyLister) List(selector labels.Selector) (ret []*v1beta1.NetReachHealthy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.NetReachHealthy))
	})
	return ret, err
}

// Get retrieves the NetReachHealthy from the index for a given name.
func (s *netReachHealthyLister) Get(name string) (*v1beta1.NetReachHealthy, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("netreachhealthy"), name)
	}
	return obj.(*v1beta1.NetReachHealthy), nil
}
