// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: agent_grpc.proto

package agentGrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecRequestMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command       string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Timeoutsecond uint64 `protobuf:"varint,2,opt,name=timeoutsecond,proto3" json:"timeoutsecond,omitempty"`
}

func (x *ExecRequestMsg) Reset() {
	*x = ExecRequestMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecRequestMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequestMsg) ProtoMessage() {}

func (x *ExecRequestMsg) ProtoReflect() protoreflect.Message {
	mi := &file_agent_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequestMsg.ProtoReflect.Descriptor instead.
func (*ExecRequestMsg) Descriptor() ([]byte, []int) {
	return file_agent_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *ExecRequestMsg) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecRequestMsg) GetTimeoutsecond() uint64 {
	if x != nil {
		return x.Timeoutsecond
	}
	return 0
}

type ExecResponseMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stdmsg string `protobuf:"bytes,1,opt,name=stdmsg,proto3" json:"stdmsg,omitempty"`
	Stderr string `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Code   int32  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ExecResponseMsg) Reset() {
	*x = ExecResponseMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecResponseMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponseMsg) ProtoMessage() {}

func (x *ExecResponseMsg) ProtoReflect() protoreflect.Message {
	mi := &file_agent_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponseMsg.ProtoReflect.Descriptor instead.
func (*ExecResponseMsg) Descriptor() ([]byte, []int) {
	return file_agent_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *ExecResponseMsg) GetStdmsg() string {
	if x != nil {
		return x.Stdmsg
	}
	return ""
}

func (x *ExecResponseMsg) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecResponseMsg) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_agent_grpc_proto protoreflect.FileDescriptor

var file_agent_grpc_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x0e, 0x45, 0x78, 0x65,
	0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x74, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x22, 0x55, 0x0a, 0x0f, 0x45,
	0x78, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x64, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x64, 0x6d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x32, 0x4e, 0x0a, 0x0a, 0x43, 0x6d, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x40, 0x0a, 0x0d, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6d,
	0x64, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x73, 0x67,
	0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_agent_grpc_proto_rawDescOnce sync.Once
	file_agent_grpc_proto_rawDescData = file_agent_grpc_proto_rawDesc
)

func file_agent_grpc_proto_rawDescGZIP() []byte {
	file_agent_grpc_proto_rawDescOnce.Do(func() {
		file_agent_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_agent_grpc_proto_rawDescData)
	})
	return file_agent_grpc_proto_rawDescData
}

var file_agent_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_agent_grpc_proto_goTypes = []interface{}{
	(*ExecRequestMsg)(nil),  // 0: proto.ExecRequestMsg
	(*ExecResponseMsg)(nil), // 1: proto.ExecResponseMsg
}
var file_agent_grpc_proto_depIdxs = []int32{
	0, // 0: proto.CmdService.ExecRemoteCmd:input_type -> proto.ExecRequestMsg
	1, // 1: proto.CmdService.ExecRemoteCmd:output_type -> proto.ExecResponseMsg
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agent_grpc_proto_init() }
func file_agent_grpc_proto_init() {
	if File_agent_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_agent_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecRequestMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecResponseMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_agent_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_grpc_proto_goTypes,
		DependencyIndexes: file_agent_grpc_proto_depIdxs,
		MessageInfos:      file_agent_grpc_proto_msgTypes,
	}.Build()
	File_agent_grpc_proto = out.File
	file_agent_grpc_proto_rawDesc = nil
	file_agent_grpc_proto_goTypes = nil
	file_agent_grpc_proto_depIdxs = nil
}
