//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpAppHealthy) DeepCopyInto(out *HttpAppHealthy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpAppHealthy.
func (in *HttpAppHealthy) DeepCopy() *HttpAppHealthy {
	if in == nil {
		return nil
	}
	out := new(HttpAppHealthy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HttpAppHealthy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpAppHealthyList) DeepCopyInto(out *HttpAppHealthyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HttpAppHealthy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpAppHealthyList.
func (in *HttpAppHealthyList) DeepCopy() *HttpAppHealthyList {
	if in == nil {
		return nil
	}
	out := new(HttpAppHealthyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HttpAppHealthyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpAppHealthySpec) DeepCopyInto(out *HttpAppHealthySpec) {
	*out = *in
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(SchedulePlan)
		(*in).DeepCopyInto(*out)
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(HttpAppHealthyTarget)
		(*in).DeepCopyInto(*out)
	}
	if in.Request != nil {
		in, out := &in.Request, &out.Request
		*out = new(NetHttpRequest)
		**out = **in
	}
	if in.SuccessCondition != nil {
		in, out := &in.SuccessCondition, &out.SuccessCondition
		*out = new(NetSuccessCondition)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpAppHealthySpec.
func (in *HttpAppHealthySpec) DeepCopy() *HttpAppHealthySpec {
	if in == nil {
		return nil
	}
	out := new(HttpAppHealthySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpAppHealthyTarget) DeepCopyInto(out *HttpAppHealthyTarget) {
	*out = *in
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = new(string)
		**out = **in
	}
	if in.TlsCa != nil {
		in, out := &in.TlsCa, &out.TlsCa
		*out = new(string)
		**out = **in
	}
	if in.Header != nil {
		in, out := &in.Header, &out.Header
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpAppHealthyTarget.
func (in *HttpAppHealthyTarget) DeepCopy() *HttpAppHealthyTarget {
	if in == nil {
		return nil
	}
	out := new(HttpAppHealthyTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetDnsTarget) DeepCopyInto(out *NetDnsTarget) {
	*out = *in
	if in.NetDnsTargetUser != nil {
		in, out := &in.NetDnsTargetUser, &out.NetDnsTargetUser
		*out = new(NetDnsTargetUserSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NetDnsTargetDns != nil {
		in, out := &in.NetDnsTargetDns, &out.NetDnsTargetDns
		*out = new(NetDnsTargetDnsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetDnsTarget.
func (in *NetDnsTarget) DeepCopy() *NetDnsTarget {
	if in == nil {
		return nil
	}
	out := new(NetDnsTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetDnsTargetDnsSpec) DeepCopyInto(out *NetDnsTargetDnsSpec) {
	*out = *in
	if in.ServiceNamespacedName != nil {
		in, out := &in.ServiceNamespacedName, &out.ServiceNamespacedName
		*out = new(string)
		**out = **in
	}
	if in.TestIPv4 != nil {
		in, out := &in.TestIPv4, &out.TestIPv4
		*out = new(bool)
		**out = **in
	}
	if in.TestIPv6 != nil {
		in, out := &in.TestIPv6, &out.TestIPv6
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetDnsTargetDnsSpec.
func (in *NetDnsTargetDnsSpec) DeepCopy() *NetDnsTargetDnsSpec {
	if in == nil {
		return nil
	}
	out := new(NetDnsTargetDnsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetDnsTargetUserSpec) DeepCopyInto(out *NetDnsTargetUserSpec) {
	*out = *in
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetDnsTargetUserSpec.
func (in *NetDnsTargetUserSpec) DeepCopy() *NetDnsTargetUserSpec {
	if in == nil {
		return nil
	}
	out := new(NetDnsTargetUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetHttpRequest) DeepCopyInto(out *NetHttpRequest) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetHttpRequest.
func (in *NetHttpRequest) DeepCopy() *NetHttpRequest {
	if in == nil {
		return nil
	}
	out := new(NetHttpRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetReachHealthy) DeepCopyInto(out *NetReachHealthy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetReachHealthy.
func (in *NetReachHealthy) DeepCopy() *NetReachHealthy {
	if in == nil {
		return nil
	}
	out := new(NetReachHealthy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetReachHealthy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetReachHealthyList) DeepCopyInto(out *NetReachHealthyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetReachHealthy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetReachHealthyList.
func (in *NetReachHealthyList) DeepCopy() *NetReachHealthyList {
	if in == nil {
		return nil
	}
	out := new(NetReachHealthyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetReachHealthyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetReachHealthySpec) DeepCopyInto(out *NetReachHealthySpec) {
	*out = *in
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(SchedulePlan)
		(*in).DeepCopyInto(*out)
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(NetReachHealthyTarget)
		(*in).DeepCopyInto(*out)
	}
	if in.Request != nil {
		in, out := &in.Request, &out.Request
		*out = new(NetHttpRequest)
		**out = **in
	}
	if in.SuccessCondition != nil {
		in, out := &in.SuccessCondition, &out.SuccessCondition
		*out = new(NetSuccessCondition)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetReachHealthySpec.
func (in *NetReachHealthySpec) DeepCopy() *NetReachHealthySpec {
	if in == nil {
		return nil
	}
	out := new(NetReachHealthySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetReachHealthyTarget) DeepCopyInto(out *NetReachHealthyTarget) {
	*out = *in
	if in.IPv4 != nil {
		in, out := &in.IPv4, &out.IPv4
		*out = new(bool)
		**out = **in
	}
	if in.IPv6 != nil {
		in, out := &in.IPv6, &out.IPv6
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetReachHealthyTarget.
func (in *NetReachHealthyTarget) DeepCopy() *NetReachHealthyTarget {
	if in == nil {
		return nil
	}
	out := new(NetReachHealthyTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetSuccessCondition) DeepCopyInto(out *NetSuccessCondition) {
	*out = *in
	if in.SuccessRate != nil {
		in, out := &in.SuccessRate, &out.SuccessRate
		*out = new(float64)
		**out = **in
	}
	if in.MeanAccessDelayInMs != nil {
		in, out := &in.MeanAccessDelayInMs, &out.MeanAccessDelayInMs
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetSuccessCondition.
func (in *NetSuccessCondition) DeepCopy() *NetSuccessCondition {
	if in == nil {
		return nil
	}
	out := new(NetSuccessCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Netdns) DeepCopyInto(out *Netdns) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Netdns.
func (in *Netdns) DeepCopy() *Netdns {
	if in == nil {
		return nil
	}
	out := new(Netdns)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Netdns) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetdnsList) DeepCopyInto(out *NetdnsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Netdns, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetdnsList.
func (in *NetdnsList) DeepCopy() *NetdnsList {
	if in == nil {
		return nil
	}
	out := new(NetdnsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetdnsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetdnsRequest) DeepCopyInto(out *NetdnsRequest) {
	*out = *in
	if in.DurationInSecond != nil {
		in, out := &in.DurationInSecond, &out.DurationInSecond
		*out = new(uint64)
		**out = **in
	}
	if in.QPS != nil {
		in, out := &in.QPS, &out.QPS
		*out = new(uint64)
		**out = **in
	}
	if in.PerRequestTimeoutInMS != nil {
		in, out := &in.PerRequestTimeoutInMS, &out.PerRequestTimeoutInMS
		*out = new(uint64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetdnsRequest.
func (in *NetdnsRequest) DeepCopy() *NetdnsRequest {
	if in == nil {
		return nil
	}
	out := new(NetdnsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetdnsSpec) DeepCopyInto(out *NetdnsSpec) {
	*out = *in
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(SchedulePlan)
		(*in).DeepCopyInto(*out)
	}
	if in.SourceAgentNodeSelector != nil {
		in, out := &in.SourceAgentNodeSelector, &out.SourceAgentNodeSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(NetDnsTarget)
		(*in).DeepCopyInto(*out)
	}
	if in.Request != nil {
		in, out := &in.Request, &out.Request
		*out = new(NetdnsRequest)
		(*in).DeepCopyInto(*out)
	}
	if in.SuccessCondition != nil {
		in, out := &in.SuccessCondition, &out.SuccessCondition
		*out = new(NetSuccessCondition)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetdnsSpec.
func (in *NetdnsSpec) DeepCopy() *NetdnsSpec {
	if in == nil {
		return nil
	}
	out := new(NetdnsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulePlan) DeepCopyInto(out *SchedulePlan) {
	*out = *in
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulePlan.
func (in *SchedulePlan) DeepCopy() *SchedulePlan {
	if in == nil {
		return nil
	}
	out := new(SchedulePlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusHistoryRecord) DeepCopyInto(out *StatusHistoryRecord) {
	*out = *in
	in.StartTimeStamp.DeepCopyInto(&out.StartTimeStamp)
	if in.EndTimeStamp != nil {
		in, out := &in.EndTimeStamp, &out.EndTimeStamp
		*out = (*in).DeepCopy()
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(string)
		**out = **in
	}
	in.DeadLineTimeStamp.DeepCopyInto(&out.DeadLineTimeStamp)
	if in.ExpectedActorNumber != nil {
		in, out := &in.ExpectedActorNumber, &out.ExpectedActorNumber
		*out = new(int)
		**out = **in
	}
	if in.FailedAgentNodeList != nil {
		in, out := &in.FailedAgentNodeList, &out.FailedAgentNodeList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SucceedAgentNodeList != nil {
		in, out := &in.SucceedAgentNodeList, &out.SucceedAgentNodeList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NotReportAgentNodeList != nil {
		in, out := &in.NotReportAgentNodeList, &out.NotReportAgentNodeList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusHistoryRecord.
func (in *StatusHistoryRecord) DeepCopy() *StatusHistoryRecord {
	if in == nil {
		return nil
	}
	out := new(StatusHistoryRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskStatus) DeepCopyInto(out *TaskStatus) {
	*out = *in
	if in.ExpectedRound != nil {
		in, out := &in.ExpectedRound, &out.ExpectedRound
		*out = new(int64)
		**out = **in
	}
	if in.DoneRound != nil {
		in, out := &in.DoneRound, &out.DoneRound
		*out = new(int64)
		**out = **in
	}
	if in.LastRoundStatus != nil {
		in, out := &in.LastRoundStatus, &out.LastRoundStatus
		*out = new(string)
		**out = **in
	}
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = make([]StatusHistoryRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskStatus.
func (in *TaskStatus) DeepCopy() *TaskStatus {
	if in == nil {
		return nil
	}
	out := new(TaskStatus)
	in.DeepCopyInto(out)
	return out
}
