// Code generated by go-swagger; DO NOT EDIT.
// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

// Package server http server API
//
//	http server
//	Schemes:
//	  unix
//	Host: localhost
//	BasePath: /
//	Version: v1
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package server
