// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package healthy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetHealthyStartupParams creates a new GetHealthyStartupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetHealthyStartupParams() *GetHealthyStartupParams {
	return &GetHealthyStartupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetHealthyStartupParamsWithTimeout creates a new GetHealthyStartupParams object
// with the ability to set a timeout on a request.
func NewGetHealthyStartupParamsWithTimeout(timeout time.Duration) *GetHealthyStartupParams {
	return &GetHealthyStartupParams{
		timeout: timeout,
	}
}

// NewGetHealthyStartupParamsWithContext creates a new GetHealthyStartupParams object
// with the ability to set a context for a request.
func NewGetHealthyStartupParamsWithContext(ctx context.Context) *GetHealthyStartupParams {
	return &GetHealthyStartupParams{
		Context: ctx,
	}
}

// NewGetHealthyStartupParamsWithHTTPClient creates a new GetHealthyStartupParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetHealthyStartupParamsWithHTTPClient(client *http.Client) *GetHealthyStartupParams {
	return &GetHealthyStartupParams{
		HTTPClient: client,
	}
}

/*
GetHealthyStartupParams contains all the parameters to send to the API endpoint

	for the get healthy startup operation.

	Typically these are written to a http.Request.
*/
type GetHealthyStartupParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get healthy startup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHealthyStartupParams) WithDefaults() *GetHealthyStartupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get healthy startup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHealthyStartupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get healthy startup params
func (o *GetHealthyStartupParams) WithTimeout(timeout time.Duration) *GetHealthyStartupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get healthy startup params
func (o *GetHealthyStartupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get healthy startup params
func (o *GetHealthyStartupParams) WithContext(ctx context.Context) *GetHealthyStartupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get healthy startup params
func (o *GetHealthyStartupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get healthy startup params
func (o *GetHealthyStartupParams) WithHTTPClient(client *http.Client) *GetHealthyStartupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get healthy startup params
func (o *GetHealthyStartupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetHealthyStartupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
