// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package healthy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetHealthyReadinessReader is a Reader for the GetHealthyReadiness structure.
type GetHealthyReadinessReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHealthyReadinessReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetHealthyReadinessOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetHealthyReadinessInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetHealthyReadinessOK creates a GetHealthyReadinessOK with default headers values
func NewGetHealthyReadinessOK() *GetHealthyReadinessOK {
	return &GetHealthyReadinessOK{}
}

/*
GetHealthyReadinessOK describes a response with status code 200, with default header values.

Success
*/
type GetHealthyReadinessOK struct {
}

// IsSuccess returns true when this get healthy readiness o k response has a 2xx status code
func (o *GetHealthyReadinessOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get healthy readiness o k response has a 3xx status code
func (o *GetHealthyReadinessOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get healthy readiness o k response has a 4xx status code
func (o *GetHealthyReadinessOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get healthy readiness o k response has a 5xx status code
func (o *GetHealthyReadinessOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get healthy readiness o k response a status code equal to that given
func (o *GetHealthyReadinessOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get healthy readiness o k response
func (o *GetHealthyReadinessOK) Code() int {
	return 200
}

func (o *GetHealthyReadinessOK) Error() string {
	return fmt.Sprintf("[GET /healthy/readiness][%d] getHealthyReadinessOK ", 200)
}

func (o *GetHealthyReadinessOK) String() string {
	return fmt.Sprintf("[GET /healthy/readiness][%d] getHealthyReadinessOK ", 200)
}

func (o *GetHealthyReadinessOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetHealthyReadinessInternalServerError creates a GetHealthyReadinessInternalServerError with default headers values
func NewGetHealthyReadinessInternalServerError() *GetHealthyReadinessInternalServerError {
	return &GetHealthyReadinessInternalServerError{}
}

/*
GetHealthyReadinessInternalServerError describes a response with status code 500, with default header values.

Failed
*/
type GetHealthyReadinessInternalServerError struct {
}

// IsSuccess returns true when this get healthy readiness internal server error response has a 2xx status code
func (o *GetHealthyReadinessInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get healthy readiness internal server error response has a 3xx status code
func (o *GetHealthyReadinessInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get healthy readiness internal server error response has a 4xx status code
func (o *GetHealthyReadinessInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get healthy readiness internal server error response has a 5xx status code
func (o *GetHealthyReadinessInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get healthy readiness internal server error response a status code equal to that given
func (o *GetHealthyReadinessInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get healthy readiness internal server error response
func (o *GetHealthyReadinessInternalServerError) Code() int {
	return 500
}

func (o *GetHealthyReadinessInternalServerError) Error() string {
	return fmt.Sprintf("[GET /healthy/readiness][%d] getHealthyReadinessInternalServerError ", 500)
}

func (o *GetHealthyReadinessInternalServerError) String() string {
	return fmt.Sprintf("[GET /healthy/readiness][%d] getHealthyReadinessInternalServerError ", 500)
}

func (o *GetHealthyReadinessInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
