// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package healthy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetHealthyStartupReader is a Reader for the GetHealthyStartup structure.
type GetHealthyStartupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHealthyStartupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetHealthyStartupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetHealthyStartupInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetHealthyStartupOK creates a GetHealthyStartupOK with default headers values
func NewGetHealthyStartupOK() *GetHealthyStartupOK {
	return &GetHealthyStartupOK{}
}

/*
GetHealthyStartupOK describes a response with status code 200, with default header values.

Success
*/
type GetHealthyStartupOK struct {
}

// IsSuccess returns true when this get healthy startup o k response has a 2xx status code
func (o *GetHealthyStartupOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get healthy startup o k response has a 3xx status code
func (o *GetHealthyStartupOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get healthy startup o k response has a 4xx status code
func (o *GetHealthyStartupOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get healthy startup o k response has a 5xx status code
func (o *GetHealthyStartupOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get healthy startup o k response a status code equal to that given
func (o *GetHealthyStartupOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get healthy startup o k response
func (o *GetHealthyStartupOK) Code() int {
	return 200
}

func (o *GetHealthyStartupOK) Error() string {
	return fmt.Sprintf("[GET /healthy/startup][%d] getHealthyStartupOK ", 200)
}

func (o *GetHealthyStartupOK) String() string {
	return fmt.Sprintf("[GET /healthy/startup][%d] getHealthyStartupOK ", 200)
}

func (o *GetHealthyStartupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetHealthyStartupInternalServerError creates a GetHealthyStartupInternalServerError with default headers values
func NewGetHealthyStartupInternalServerError() *GetHealthyStartupInternalServerError {
	return &GetHealthyStartupInternalServerError{}
}

/*
GetHealthyStartupInternalServerError describes a response with status code 500, with default header values.

Failed
*/
type GetHealthyStartupInternalServerError struct {
}

// IsSuccess returns true when this get healthy startup internal server error response has a 2xx status code
func (o *GetHealthyStartupInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get healthy startup internal server error response has a 3xx status code
func (o *GetHealthyStartupInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get healthy startup internal server error response has a 4xx status code
func (o *GetHealthyStartupInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get healthy startup internal server error response has a 5xx status code
func (o *GetHealthyStartupInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get healthy startup internal server error response a status code equal to that given
func (o *GetHealthyStartupInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get healthy startup internal server error response
func (o *GetHealthyStartupInternalServerError) Code() int {
	return 500
}

func (o *GetHealthyStartupInternalServerError) Error() string {
	return fmt.Sprintf("[GET /healthy/startup][%d] getHealthyStartupInternalServerError ", 500)
}

func (o *GetHealthyStartupInternalServerError) String() string {
	return fmt.Sprintf("[GET /healthy/startup][%d] getHealthyStartupInternalServerError ", 500)
}

func (o *GetHealthyStartupInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
