// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package healthy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetHealthyReadinessParams creates a new GetHealthyReadinessParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetHealthyReadinessParams() *GetHealthyReadinessParams {
	return &GetHealthyReadinessParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetHealthyReadinessParamsWithTimeout creates a new GetHealthyReadinessParams object
// with the ability to set a timeout on a request.
func NewGetHealthyReadinessParamsWithTimeout(timeout time.Duration) *GetHealthyReadinessParams {
	return &GetHealthyReadinessParams{
		timeout: timeout,
	}
}

// NewGetHealthyReadinessParamsWithContext creates a new GetHealthyReadinessParams object
// with the ability to set a context for a request.
func NewGetHealthyReadinessParamsWithContext(ctx context.Context) *GetHealthyReadinessParams {
	return &GetHealthyReadinessParams{
		Context: ctx,
	}
}

// NewGetHealthyReadinessParamsWithHTTPClient creates a new GetHealthyReadinessParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetHealthyReadinessParamsWithHTTPClient(client *http.Client) *GetHealthyReadinessParams {
	return &GetHealthyReadinessParams{
		HTTPClient: client,
	}
}

/*
GetHealthyReadinessParams contains all the parameters to send to the API endpoint

	for the get healthy readiness operation.

	Typically these are written to a http.Request.
*/
type GetHealthyReadinessParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get healthy readiness params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHealthyReadinessParams) WithDefaults() *GetHealthyReadinessParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get healthy readiness params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHealthyReadinessParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get healthy readiness params
func (o *GetHealthyReadinessParams) WithTimeout(timeout time.Duration) *GetHealthyReadinessParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get healthy readiness params
func (o *GetHealthyReadinessParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get healthy readiness params
func (o *GetHealthyReadinessParams) WithContext(ctx context.Context) *GetHealthyReadinessParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get healthy readiness params
func (o *GetHealthyReadinessParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get healthy readiness params
func (o *GetHealthyReadinessParams) WithHTTPClient(client *http.Client) *GetHealthyReadinessParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get healthy readiness params
func (o *GetHealthyReadinessParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetHealthyReadinessParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
