// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2023 Authors of kdoctor-io
// SPDX-License-Identifier: Apache-2.0

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EchoBody echo request body args
//
// swagger:model EchoBody
type EchoBody struct {

	// test1
	Test1 string `json:"test1,omitempty"`

	// test2
	Test2 string `json:"test2,omitempty"`
}

// Validate validates this echo body
func (m *EchoBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this echo body based on context it is used
func (m *EchoBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EchoBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EchoBody) UnmarshalBinary(b []byte) error {
	var res EchoBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
