name: Auto Nightly CI

permissions: write-all
on:
  schedule:
    # each day
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  call_ci_v1_32:
    uses: ./.github/workflows/auto-pr-ci.yaml
    secrets: inherit
    with:
      kindNodeImage: kindest/node:v1.32.11
      ipfamily: all

  call_ci_v1_33:
    # it races to upload images and artifacts when all jobs running, so just call_ci_v1_32 builds image
    needs: [call_ci_v1_32]
    uses: ./.github/workflows/auto-pr-ci.yaml
    secrets: inherit
    with:
      kindNodeImage: kindest/node:v1.33.7
      ipfamily: dual
      justE2E: 'true'

  call_ci_v1_34:
    # it races to upload images and artifacts when all jobs running, so just call_ci_v1_32 builds image
    needs: [call_ci_v1_32]
    uses: ./.github/workflows/auto-pr-ci.yaml
    secrets: inherit
    with:
      kindNodeImage: kindest/node:v1.34.3
      ipfamily: dual
      justE2E: 'true'

  creat_issue:
    runs-on: ubuntu-latest
    needs: [call_ci_v1_32, call_ci_v1_33, call_ci_v1_34]
    # https://docs.github.com/en/actions/learn-github-actions/contexts#jobs-context
    if: ${{ always() && ( needs.call_ci_v1_32.result == 'failure' || needs.call_ci_v1_33.result == 'failure' || needs.call_ci_v1_34.result == 'failure' ) }}
    steps:
      - name: echo
        run: |
          echo ${{ github.repository }}
          echo ${{ github.repository_owner }}
          echo "TIMESTAMP=`date +%Y-%m-%d`" >> $GITHUB_ENV

      - name: create an issue
        uses: dacbd/create-issue-action@v1.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          #owner: kdoctor-io
          #repo: rocktemplae
          title: "Night CI ${{ ENV.TIMESTAMP }}: Failed"
          body: |
            action url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          labels: "kind/ci-bug"
          assignees: "ii2day"
