name: Auto Nightly CI

permissions: write-all
on:
  schedule:
    # each day
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  call_ci_latest:
    uses: ./.github/workflows/auto-pr-ci.yaml
    secrets: inherit
    with:
      ipfamily: all

  call_ci_v1_22:
    # it races to upload images and artifacts when all jobs running , so just call_ci_latest build image
    needs: [call_ci_latest]
    uses: ./.github/workflows/auto-pr-ci.yaml
    secrets: inherit
    with:
      kindNodeImage: kindest/node:v1.22.17
      ipfamily: dual
      justE2E: 'true'

  call_ci_v1_23:
    # it races to upload images and artifacts when all jobs running , so just call_ci_latest build image
    needs: [call_ci_latest]
    uses: ./.github/workflows/auto-pr-ci.yaml
    secrets: inherit
    with:
      kindNodeImage: kindest/node:v1.23.17
      ipfamily: dual
      justE2E: 'true'

  call_ci_v1_24:
    # it races to upload images and artifacts when all jobs running , so just call_ci_latest build image
    needs: [call_ci_latest]
    uses: ./.github/workflows/auto-pr-ci.yaml
    secrets: inherit
    with:
      kindNodeImage: kindest/node:v1.24.13
      ipfamily: dual
      justE2E: 'true'

  call_ci_v1_25:
    # it races to upload images and artifacts when all jobs running , so just call_ci_latest build image
    needs: [call_ci_latest]
    uses: ./.github/workflows/auto-pr-ci.yaml
    secrets: inherit
    with:
      kindNodeImage: kindest/node:v1.25.9
      ipfamily: dual
      justE2E: 'true'

  call_ci_v1_26:
    # it races to upload images and artifacts when all jobs running , so just call_ci_latest build image
    needs: [call_ci_latest]
    uses: ./.github/workflows/auto-pr-ci.yaml
    secrets: inherit
    with:
      kindNodeImage: kindest/node:v1.26.4
      ipfamily: dual
      justE2E: 'true'

  call_ci_v1_27:
    # it races to upload images and artifacts when all jobs running , so just call_ci_latest build image
    needs: [call_ci_latest]
    uses: ./.github/workflows/auto-pr-ci.yaml
    secrets: inherit
    with:
      kindNodeImage: kindest/node:v1.27.1
      ipfamily: dual
      justE2E: 'true'

  call_ci_v1_28:
    # it races to upload images and artifacts when all jobs running , so just call_ci_latest build image
    needs: [ call_ci_latest ]
    uses: ./.github/workflows/auto-pr-ci.yaml
    secrets: inherit
    with:
      kindNodeImage: kindest/node:v1.28.0
      ipfamily: dual
      justE2E: 'true'

  creat_issue:
    runs-on: ubuntu-latest
    needs: [call_ci_latest, call_ci_v1_22, call_ci_v1_23, call_ci_v1_24, call_ci_v1_25, call_ci_v1_26, call_ci_v1_27, call_ci_v1_28]
    # https://docs.github.com/en/actions/learn-github-actions/contexts#jobs-context
    if: ${{ always() && ( needs.call_ci_latest.result == 'failure' || needs.call_ci_v1_22.result == 'failure' || needs.call_ci_v1_23.result == 'failure' || needs.call_ci_v1_24.result == 'failure' || needs.call_ci_v1_25.result == 'failure' || needs.call_ci_v1_26.result == 'failure' || needs.call_ci_v1_27.result == 'failure' || needs.call_ci_v1_28.result == 'failure' ) }}
    steps:
      - name: echo
        run: |
          echo ${{ github.repository }}
          echo ${{ github.repository_owner }}
          echo "TIMESTAMP=`date +%Y-%m-%d`" >> $GITHUB_ENV

      - name: create an issue
        uses: dacbd/create-issue-action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          #owner: kdoctor-io
          #repo: rocktemplae
          title: "Night CI ${{ ENV.TIMESTAMP }}: Failed"
          body: |
            action url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          labels: "kind/ci-bug"
          assignees: "ii2day"