name: Call Trivy

permissions: write-all

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

env:
  kdoctor_agent_image: image-tar-kdoctor-agent/kdoctor-agent.tar
  kdoctor_controller_image: image-tar-kdoctor-controller/kdoctor-controller.tar

jobs:
  e2e_against_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ inputs.ref }}

      # download all artifact
      # https://github.com/actions/download-artifact#download-all-artifacts
      - name: Download images
        uses: actions/download-artifact@v3
        with:
          path: output/artifact-trivy

      - name: List downloaded files
        run:  |
          ls -al output/artifact-trivy

      # https://github.com/aquasecurity/trivy-action/issues/389
      - name: Load And Scan Kdoctor-agent Image
        uses: aquasecurity/trivy-action@0.28.0
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db,ghcr.io/aquasecurity/trivy-db
        with:
          input: output/artifact-trivy/${{ env.kdoctor_agent_image }}
          severity: 'CRITICAL,HIGH'

      - name: Load And Scan Kdoctor-controller Images
        uses: aquasecurity/trivy-action@0.28.0
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db,ghcr.io/aquasecurity/trivy-db
        with:
          input: output/artifact-trivy/${{ env.kdoctor_controller_image }}
          severity: 'CRITICAL,HIGH'
