name: Call Trivy

permissions: write-all

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  e2e_against_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ inputs.ref }}

      # download all artifact
      # https://github.com/actions/download-artifact#download-all-artifacts
      - name: Download images
        uses: actions/download-artifact@v4
        with:
          path: output/artifact-trivy

      - name: Load And Scan Images
        run: |
          PROJECT_DIR=`pwd`
          cd output/artifact-trivy
          ls
          ALL_DIR=`ls`
          IMAGE_DIR=""
          for ITEM in $ALL_DIR ; do
              grep -E "^image-tar" <<< "${ITEM}" &>/dev/null && IMAGE_DIR+=" ${ITEM} "
          done
          echo "IMAGE_DIR=${IMAGE_DIR}"
          RESULT=true
          for ITEM in $IMAGE_DIR ; do
              TAR_FILES=`ls ${ITEM}`
              for TAR in $TAR_FILES ; do
                echo "image tar ${ITEM}/${TAR}"
                cat ${ITEM}/${TAR} |  docker import - ${TAR%*.tar}:${{ inputs.ref }}
                echo "---------trivy checkout image ${TAR%*.tar}:${{ inputs.ref }} --------------------"
                make -C ${PROJECT_DIR} lint_image_trivy -e IMAGE_NAME=${TAR%*.tar}:${{ inputs.ref }} \
                    || { RESULT=false ; echo "error, image ${TAR%*.tar}:${{ inputs.ref }} is bad" ; }
              done
          done
          docker images
          if [ "$RESULT" != "true" ]; then
              echo "error, image is not secure, see detail on Step 'Load And Scan Images' "
              exit 1
          else
              exit 0
          fi
